import {routes,sources,itineraries,extras,trains,lodging,packing,credits} from './data.js';
import {mountJourneyAnimation} from './journey-animation.js';
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
const money=n=>new Intl.NumberFormat('ru-KZ',{maximumFractionDigits:0}).format(Math.round(n))+' ₸';
const ext=(t,u,c='text-link')=>`<a class="${c}" href="${u}" target="_blank" rel="noopener noreferrer">${t}</a>`;
const link=(t,k,c)=>ext(t,sources[k],c);
const bounded=(v,min,max,f)=>v!==null&&v!==''&&Number.isFinite(Number(v))?Math.max(min,Math.min(max,Number(v))):f;
const q=new URLSearchParams(location.search);
const state={route:routes[q.get('r')]?q.get('r'):'A',day:12,scope:q.get('scope')==='2'?2:1,fx:bounded(q.get('fx'),50,100,70),food:bounded(q.get('food'),300,1500,600),reserve:bounded(q.get('reserve'),0,100000,40000),air:q.has('air')?bounded(q.get('air'),0,1000000,null):null,fast:q.get('fast')==='1',late:q.get('late')==='1',extras:(q.get('extras')||'').split(',').filter(x=>extras.some(e=>e.id===x)),checks:{}};
try{const c=JSON.parse(localStorage.getItem('china2026-checklist')||'{}');if(c&&typeof c==='object'&&!Array.isArray(c))state.checks=c;}catch{}
let toastTimer;
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
function calculate(s=state){const r=routes[s.route],air=s.air??(r.air-(s.route==='B'&&s.late?9663:0)),rail=(r.rail+(s.route==='A'&&s.fast?94:0))*s.fx,active=extras.filter(e=>s.extras.includes(e.id)&&e.available.includes(s.route));const rows=[['Перелёты',air,'lime'],['Поезда',rail,'purple'],['Жильё',r.hotel*s.fx,'blue'],['Еда',s.food*s.fx,'orange'],['Места и аттракционы',r.entry*s.fx,'mint'],['Местные дороги',r.local*s.fx,'gray'],['Связь и страховка',12000,'gray'],['Аэропорт Астаны',4000,'gray']];const extra=active.reduce((a,e)=>a+e.cny*s.fx,0);if(extra)rows.push(['Ваши дополнения',extra,'orange']);const expenses=rows.reduce((a,r)=>a+r[1],0);return{air,rail,intercity:air+rail,expenses,total:expenses+s.reserve,left:500000-expenses-s.reserve,rows,active};}
function syncUrl(){const p=new URLSearchParams({r:state.route});if(state.fast&&state.route==='A')p.set('fast','1');if(state.late&&state.route==='B')p.set('late','1');for(const [k,v]of Object.entries({fx:70,food:600,reserve:40000,scope:1}))if(state[k]!==v)p.set(k,state[k]);if(state.air!==null)p.set('air',state.air);const ex=calculate().active.map(e=>e.id);if(ex.length)p.set('extras',ex.join(','));history.replaceState(null,'',location.pathname+'?'+p+location.hash);}
const heading=(n,title,aside='')=>`<div class="section-heading"><div><p class="eyebrow">${n}</p><h2>${title}</h2></div>${aside?`<p>${aside}</p>`:''}</div>`;
const details=(title,body)=>`<details class="accordion"><summary>${title}<span class="plus">+</span></summary><div class="details-body">${body}</div></details>`;

$('#planner-content').innerHTML=`
<section id="journey-section" class="journey-section"><div class="minor-heading"><h3>Как движемся</h3><span class="meta">Нажмите ▶ и проследите весь маршрут</span></div><div id="trip-animation" class="trip-animation"></div><div id="journey" class="journey"></div><div id="inclusions" class="inclusions"></div></section>
<section id="days" class="block">${heading('02 / ПЛАН НА КАЖДЫЙ ДЕНЬ','У каждого дня — своя история.','Нажмите на дату.<br>Куда едем и где спим — всё рядом.')}<div id="day-tabs" class="day-tabs" role="tablist" aria-label="Дни поездки"></div><article id="day-panel" class="day-panel" role="tabpanel" tabindex="0"></article>${details('Вся поездка одним взглядом','<div id="all-days"></div>')}</section>
<section id="budget" class="block">${heading('03 / СЧИТАЕМ БЕЗ МАГИИ','Меньше на дорогу.<br>Больше на впечатления.')}<div class="segmented" role="group" aria-label="Показывать бюджет"><button data-scope="1">На одного</button><button data-scope="2">На двоих</button></div><div class="budget-layout"><div class="budget-editor"><div id="budget-controls"></div><div class="extras-heading"><h3>Добавим впечатлений?</h3><p>Сумма изменится сразу. Время для дополнений нужно освободить в программе.</p></div><div id="extras" class="extras"></div></div><aside class="budget-result" aria-label="Итоговый бюджет"><div class="budget-result-top"><span id="budget-scope"></span><span class="budget-badge" id="budget-status"></span></div><div id="budget-total" class="budget-total"></div><p id="reserve-note"></p><div class="budget-meter"><span id="meter-fill"></span></div><div class="budget-left" id="budget-left"></div><div id="breakdown" class="budget-breakdown"></div><div class="budget-bro"><img src="assets/friend-sticker.png" alt="" width="72" height="80" loading="lazy"><p id="budget-bro-quote" aria-live="polite"></p></div><p class="budget-disclaimer">Смета, не готовый тур. Без сданного багажа и платного сна на пересадках. Цены и комиссии могут изменить итог.</p><button class="button wide" id="share-budget">Отправить этот вариант другу</button><button class="reset-button" id="reset-budget">Вернуть исходный расчёт</button></aside></div></section>
<section id="tickets" class="block">${heading('04 / БИЛЕТЫ, КОТОРЫЕ МЕНЯЮТ ВСЁ','В Китай через Урумчи.','Международный туда-обратно найден<br>за <b class="accent">73 858 ₸ на человека</b>.')}<div class="flight-grid" id="flights"></div><div class="travel-note"><span class="note-symbol">i</span><div><b>Самостоятельные пересадки</b><p id="layover-note"></p><p>20 ноября в 02:00 вылет из Урумчи, в 01:50 прилёт в Астану. В аэропорт приезжаем <b>вечером 19-го</b>. Все часы местные, Китай +3 часа к Астане.</p></div></div>${details('Поезда, цены и китайские названия станций','<p>Ноябрьских билетов ещё нет в продаже. Это текущие примеры, которые нужно подтвердить. Предзаказ посредника ещё не билет.</p><div id="train-table" class="table-scroll"></div><p class="important-note">В A/B: Иян 益阳 и Иян-Южный 益阳南 — разные вокзалы, заложено около трёх часов и такси. На ночь брать 硬卧 / hard sleeper, не сидячее и не стоячее место.</p>')}${details('Где жить: районы и целевые цены','<p>Ниже бюджет за <b>номер на двоих</b>, не подтверждённые свободные номера. Проверить две кровати, отопление, поздний заезд и оформление гостей по паспортам Казахстана.</p><div id="hotel-table" class="table-scroll"></div><p class="meta">Сначала ночуем у восточного входа в лесной парк, затем в центре Чжанцзяцзе у отправления на Тяньмэнь. В Чунцине проверять реальный вход в здание и лестницы.</p>')}</section>
<section id="compare" class="block">${heading('05 / А ЕСЛИ ПО-ДРУГОМУ?','Шесть способов собрать поездку.','Исходный курс 70 ₸ за CNY.<br>Вся поездка — с резервом 40 000 ₸.')}<div class="comparison-scroll" id="comparison"></div><div class="insight-grid"><article class="insight"><span class="insight-number">−105<span>тыс. ₸</span></span><h3>Экономия на межгороде</h3><p>A — около 215 тысяч вместо 320 тысяч в первой схеме с въездом через Пекин. На двоих разница около 210 тысяч.</p></article><article class="insight"><span class="insight-number">3<span>ч 25 мин</span></span><h3>Урумчи — Сиань самолётом</h3><p>Найдено за 43 385 ₸. D2718: 14 ч 46 мин, около 51 520 ₸. Полка Z66: ~31 255 ₸, но 25 часов в пути. ${link('Сравнить поезда','urcTrain')}</p></article><article class="insight"><span class="insight-number">11—20<span>ноября</span></span><h3>Даты экономят деньги</h3><p>10–19 ноября Урумчи стоил 115 899 ₸ туда-обратно с долгой пересадкой туда. 11–20 — 73 858 ₸ прямыми рейсами. Разница 42 041 ₸.</p></article></div>${details('Алматы, прямой Сиань и длинные поезда: что ещё проверено','<p>Алматы — Сиань 10 ноября найден за 94 526 ₸ в одну сторону, ещё до дороги из Астаны. Выгода полной поездки не доказана. Астана — Сиань туда-обратно с возвращением 19-го: 226 408 ₸. Дешевле, за 192 972 ₸, прилёт был 20-го: от вылета 10-го это уже 11 дней.</p><p>Спальный поезд Урумчи — Сиань экономит около 12 тысяч против найденного самолёта, но отнимает почти сутки. Придётся убрать программу. Наземный путь до Китая и длинные пересадки в Инине — такой же обмен денег на дни.</p><p class="meta">Это проверенные направления и основные альтернативы, не обещание перебрать все тарифы мира. Цены из выдачи 29.09.2026 без финальной оплаты.</p>')}</section>
<section id="places" class="block">${heading('06 / РАДИ ЭТОГО И ЕДЕМ','Места, которые не забудутся.','Бесплатные виды и впечатления,<br>на которых не экономим.')}<div class="place-gallery">${[['zhangjiajie.jpg','ВО ВСЕХ A/B/C','Горы «Аватара»','Юаньцзяцзе, Байлун и Тяньцзы. Целый день для панорам, а не короткий забег между автобусами.','park'],['chongqing.png','БОЛЬШЕ ВРЕМЕНИ В C','Ночной Чунцин','Поезд через дом, Шаньчэнсян, Куйсинлоу и Хунъядун. Городские виды почти бесплатны. В A/B поздний приезд: подсветка не гарантирована.',null],['mutianyu.jpg','МАРШРУТ B','Великая стена','Мутяньюй: виды на горные хребты, кресельный подъёмник и тобогган по погоде.','wall']].map(([img,tag,title,desc,key])=>`<article class="place-card"><img src="assets/${img}" alt="${title}" loading="lazy" width="1280" height="853"><div><span class="place-tag">${tag}</span><h3>${title}</h3><p>${desc}</p>${key?link('Источник и детали',key):''}</div></article>`).join('')}</div><div class="two-notes"><article class="travel-note"><span class="note-symbol">!</span><div><b>Тяньмэнь: канатки меняются</b><p>Верхний участок длинной канатки реконструируют с ноября 2025. Подтверждения открытия к поездке нет. Проверить актуальную схему. ${link('Объявление','tianmen')}</p></div></article><article class="travel-note"><span class="note-symbol">!</span><div><b>Банджи — отдельное решение</b><p>1 998 CNY прыжок + 178 вход на мост = ~152 320 ₸ до дороги. Нужны полдня, подходящая страховка и перестройка программы. ${link('Оператор','bungee')}</p></div></article></div></section>
<section id="prepare" class="block">${heading('07 / СОБИРАЕМСЯ БЕЗ СУЕТЫ','Чтобы в Китае просто гулять.')}<div class="prepare-grid"><div><div class="minor-heading"><h3>Что подготовить</h3><span class="meta" id="check-progress"></span></div><p class="meta">Галочки сохраняются в этом браузере. У друга свой список.</p><div id="packing" class="packing"></div></div><div><h3>Когда что покупать</h3><div id="calendar" class="calendar"></div></div></div><div class="practical-grid">${details('Въезд, паспорт и регистрация',`<p>Гражданам Казахстана для туризма по действующему соглашению виза не нужна: до 30 дней за въезд и 90 за 180 дней. Перед поездкой перепроверить правила. Сохранить обратный билет, адрес первого отеля и копии документов офлайн.</p><p>Отель оформляет регистрацию проживания. Практический запас срока паспорта — 6 месяцев; обязательные требования к вашим документам уточнить у перевозчика.</p>${link('МИД Казахстана','visa')} · ${link('Карточка въезда NIA','arrival')}`)}${details('Деньги, интернет и приложения',`<p>Alipay и WeChat настроить дома. Иметь запасную карту и 300–500 CNY наличными каждому — это часть бюджета. Kaspi через Alipay+ работает у участвующих продавцов, не у любого QR. Международная карта может добавлять комиссию.</p><p>У обоих независимый интернет: eSIM/роуминг с заявленным доступом к нужным приложениям. Нужны Trip.com/12306, Amap или Apple Maps, DiDi и переводчик. Адреса сохранять по-китайски.</p>${link('Инструкция Kaspi','kaspi')} · ${link('12306','rail')}`)}${details('Фразы, павербанк и важные мелочи',`<p><b>Гостинице:</b> «Двое с паспортами Казахстана. Можно заселиться и оформить регистрацию?»</p><p class="chinese">我们两位持哈萨克斯坦护照，可以入住并办理住宿登记吗？</p><p>Неостро: <b>不辣</b>. Слабая острота: <b>微辣</b>. Разделённый котёл: <b>鸳鸯锅</b>. Даже «слабо» в Чунцине бывает остро.</p><p>На внутренних рейсах павербанк с читаемой CCC/3C, допустимой ёмкостью и не из отозванной партии; в ручной клади. ${link('Правило CAAC','power')}</p><p>Полиция 110, скорая 120. Телефон страховщика хранить офлайн.</p>`)}</div></section>
<section class="final-card"><div><p class="eyebrow">РЕШАЕМ ВДВОЁМ</p><h2>Выбери свой Китай.<br>И отправь другу.</h2><p>Ссылка сохранит маршрут, настройки бюджета и дополнения. Сравните ваши версии и решите, куда хочется больше.</p></div><div><button class="button" id="share-bottom">Скопировать мой вариант</button><a class="pdf-link" href="assets/china-guide.pdf" download>Забрать 16-страничный PDF</a></div></section>
${details('Источники, дата проверки и авторы фотографий',`<p><b>Проверено 29 сентября 2026.</b> Авиацены из Trip.com: два взрослых, KZT. Финальная оплата и применимость Exclusive fare не проверены. Это предложения для повторного поиска, не удержанные места. Цена у авиакомпании отдельно не подтверждена.</p><p>Ноябрьских поездов ещё нет в продаже: номера и время — текущие ориентиры Ctrip. У 12306 обычно 15 дней продажи с учётом дня поездки, время старта зависит от станции. Отели и бытовые расходы — целевые бюджеты.</p><div class="source-links">${Object.entries({urc:'Астана — Урумчи',xian:'Урумчи — Сиань',beijing:'Урумчи — Пекин',chengdu:'Урумчи — Чэнду',back:'Чунцин — Урумчи',rail:'Поезда 12306',army:'Терракотовая армия',panda:'Панды',wall:'Мутяньюй',palace:'Дворцовый музей',shaolin:'Шаолинь',park:'Лесной парк',tianmen:'Тяньмэнь',furong:'Фужун',bungee:'Банджи',visa:'Безвиз',baggage:'Багаж',checkin:'Регистрация',power:'Павербанки'}).map(([k,t])=>link(t,k)).join('')}</div><h4>Фотографии</h4><p>Реальные фотографии, не прогноз вида в ноябре. В карточках отображаются с кадрированием. Исходные изображения сохраняют свои лицензии.</p>${credits.map(c=>`<p class="credit">${ext(c.name,c.url)} — ${c.author} / Wikimedia Commons, ${ext(c.license,c.licenseUrl)}.</p>`).join('')}<p class="meta">Сайт не продаёт билеты. Нет рекламы и аналитики. Настройки в ссылке, чек-лист в браузере. PDF содержит исходные планы, а не изменения калькулятора.</p>`)}
<dialog id="regional" aria-labelledby="regional-title"><button class="dialog-close" aria-label="Закрыть описание Синьцзяна">×</button><p class="eyebrow">D / ПРЕДВАРИТЕЛЬНЫЙ ЭСКИЗ</p><h2 id="regional-title">Другой Китай.<br>Меньше перелётов.</h2><p>Урумчи, Турфан и Кашгар вместо Стены, Шаолиня и «Аватара». Межгород ~125–145 тысяч ₸ каждому; полной сметы пока нет.</p><ol class="regional-days"><li><b>11–12:</b> перелёт в Урумчи, отдых и город.</li><li><b>13:</b> Турфан с возвращением.</li><li><b>14–15:</b> длинный поезд в Кашгар, спальная полка.</li><li><b>15–16:</b> Кашгар.</li><li><b>17–18:</b> обратный поезд в Урумчи.</li><li><b>18–19:</b> Урумчи, день запаса перед рейсом.</li><li><b>20:</b> вылет 02:00, прилёт в Астану 01:50.</li></ol><p class="important-note">73 858 ₸ авиация + две полки примерно по 317,5–436 CNY + Турфан туда-обратно по 33–52 CNY. Обратная полка оценена симметрично. Конкретные ноябрьские поезда, отели, зимние экскурсии и допуски в приграничные районы не проверены. Памир не включён.</p><p>${ext('Кашгар: поезда','https://www.travelchinaguide.com/china-trains/urumqi-kashgar.htm')} · ${ext('Турфан: поезда','https://trains.ctrip.com/TrainBooking/wulumuqi-tulufan/')}</p><button class="button dialog-done">Вернуться к сравнению</button></dialog>`;


let broAdviceIndex=0;
const broAdvice=[
  'Я просто спросил: «А давай в Китай?» Теперь у нас целая экспедиция.',
  'Если потеряемся в Чунцине, встречаемся на первом этаже. Только сначала выясним, на каком.',
  'Рюкзак — семь килограммов. Амбиции — без ограничений.',
  'Секретный план: поесть лапши. Потом ещё раз проверить план.',
  'Главное — не сказать «нам не остро» слишком уверенно.',
  'Беру только самое нужное: паспорт, телефон и тебя.'
];
function updateBro(c){
  const quote=$('#budget-bro-quote');
  if(quote)quote.textContent=c.left<0?'Бро, мы планировали увидеть мир, а не продать квартиру.':c.left<20000?'Проходим по бюджету. Сувенирного дракона берём маленького.':'Одобряю. На лапшу и внезапные приключения остаётся.';
  const routeQuotes={A:'Терракотовые воины стоят две тысячи лет. А мы один поезд выдержим.',B:'Стена, Шаолинь, «Аватар». Выспимся, когда вернёмся.',C:'Панды, лапша, неон. Я официально за этот научный маршрут.'};
  $('#crew-quote').textContent=routeQuotes[state.route];
}
$('#crew-advice').onclick=()=>{$('#crew-quote').textContent=broAdvice[broAdviceIndex++%broAdvice.length];const photo=$('.crew-photo');photo.classList.remove('crew-nod');void photo.offsetWidth;photo.classList.add('crew-nod');};

function renderSpotlight(){const r=routes[state.route],c=calculate();$$('[data-route]').forEach(b=>{b.classList.toggle('selected',b.dataset.route===state.route);b.setAttribute('aria-pressed',String(b.dataset.route===state.route));});$('#route-spotlight').innerHTML=`<div class="spotlight-copy"><p class="eyebrow">МАРШРУТ ${state.route} / ${r.tag}</p><h3>${r.title}</h3><p>${r.description}</p><div class="quick-stats"><span><b id="spot-intercity">${money(c.intercity)}</b>межгород / чел.</span><span><b>${r.trainNights} ${r.trainNights===1?'ночь':r.trainNights===0?'ночей':'ночи'}</b>в поезде</span><span><b id="spot-left">${money(c.left)}</b><span id="spot-left-label">свободно до лимита</span></span></div></div><div class="spotlight-visual"><img src="assets/${r.image}" alt="${r.alt}" width="1280" height="853" fetchpriority="high"><div class="photo-caption"><span>${r.han}</span><strong>${r.place}</strong><small>${r.caption}</small></div></div>`;}
function renderJourney(){const r=routes[state.route];$('#journey').innerHTML=r.path.map((city,i)=>`<div class="journey-stop ${i===0||i===r.path.length-1?'endpoint':''}"><span>${String(i+1).padStart(2,'0')}</span><b>${city}</b></div>`).join('');$('#inclusions').innerHTML=`<div>${r.included.map(x=>`<span class="included">✓ ${x}</span>`).join('')}</div><p>Здесь нет: ${r.missed.join(', ')}.</p>`;mountJourneyAnimation({route:state.route,fast:state.fast,late:state.late,onDay:date=>{state.day=date;renderDay();}});}
function currentDay(date){const d=structuredClone(itineraries[state.route].find(d=>d.date===date));if(state.route==='A'&&state.fast&&date===13){d.steps[1]=['После музея','Вернуться за вещами и выехать на Xi’an North 西安北 с запасом.'];d.steps[2]=['18:07–19:47','Ориентир G2022 до Luoyang Longmen 洛阳龙门, 164 CNY. Затем дорога в отель.'];d.tip='Выбран быстрый поезд. Его вокзалы отличаются от обычного D40.';}if(state.route==='B'&&state.late&&date===12){d.title='День пересадки, вечер в Пекине';d.steps=[['01:00','Прилёт в Урумчи, въезд и длинная пересадка. Платный отдых не включён.'],['16:55–20:45','Прямой Air China в Пекин. Найденная цена 63 104 ₸.'],['Вечером','Дорога в отель, заселение и сон.']];d.tip='Вечерний рейс экономит 9 663 ₸, но убирает дневные прогулки и Запретный город.';}return d;}
function renderDay(){const d=currentDay(state.day);$('#day-tabs').innerHTML=Array.from({length:10},(_,i)=>i+11).map(n=>`<button class="day-tab ${n===state.day?'active':''}" role="tab" id="day-${n}" data-day="${n}" aria-controls="day-panel" aria-selected="${n===state.day}" tabindex="${n===state.day?0:-1}"><span>День ${n-10}</span><b>${n}</b><small>ноября</small></button>`).join('');$('#day-panel').setAttribute('aria-labelledby','day-'+state.day);$('#day-panel').innerHTML=`<div class="day-heading"><span class="day-big">${d.date}<small>НОЯБРЯ</small></span><span class="day-city">${d.city}</span><div class="night-label"><span>ГДЕ СПИМ</span><b>${d.sleep}</b></div></div><div class="day-story"><h3>${d.title}</h3><div class="day-steps">${d.steps.map(([t,p])=>`<div><span>${t}</span><p>${p}</p></div>`).join('')}</div><div class="day-tip"><b>На заметку</b><p>${d.tip}</p>${link('Источник и детали',d.source)}</div></div>`;$('#all-days').innerHTML=itineraries[state.route].map(x=>`<button class="compact-day" data-jump="${x.date}"><span>${x.date}.11</span><b>${currentDay(x.date).title}</b><small>${x.sleep}</small></button>`).join('');$$('[data-day]').forEach(b=>{b.onclick=()=>{state.day=Number(b.dataset.day);renderDay();$('#day-'+state.day).focus({preventScroll:true});};b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();state.day=e.key==='Home'?11:e.key==='End'?20:Math.max(11,Math.min(20,state.day+(e.key==='ArrowRight'?1:-1)));renderDay();$('#day-'+state.day).focus();};});$$('[data-jump]').forEach(b=>b.onclick=()=>{state.day=Number(b.dataset.jump);renderDay();$('#days').scrollIntoView();});}
function renderControls(){const c=calculate();$('#budget-controls').innerHTML=`<h3>Соберите свой вариант</h3><p class="muted">Настройки ниже — на человека.</p><div class="control-group"><label for="fx">Курс юаня <output id="fx-output">${state.fx} ₸</output></label><input id="fx" type="range" min="50" max="100" step="1" value="${state.fx}"><p class="input-help">В исходном плане 70 ₸. Это допущение, не прогноз.</p></div><div class="control-pair"><div><label for="food">Еда на поездку, CNY</label><input id="food" type="number" min="300" max="1500" step="50" value="${state.food}" inputmode="numeric"><p class="input-help">600 CNY на 9 дней расходов.</p></div><div><label for="reserve">Резерв, ₸</label><input id="reserve" type="number" min="0" max="100000" step="5000" value="${state.reserve}" inputmode="numeric"><p class="input-help">40 000 ₸ на изменения и сбои.</p></div></div><div class="control-group"><label for="air">Все четыре перелёта, ₸</label><input id="air" type="number" min="0" max="1000000" step="1000" value="${c.air}" inputmode="numeric"><p class="input-help">Подставьте итог, если цена при покупке изменилась.</p></div>${state.route==='A'?`<label class="switch-option"><input id="fast" type="checkbox" ${state.fast?'checked':''}><span class="switch-art"></span><span><b>Сиань — Лоян скоростным поездом</b><small>+94 CNY, примерно на 3 часа быстрее. Другие вокзалы.</small></span></label>`:state.route==='B'?`<label class="switch-option"><input id="late" type="checkbox" ${state.late?'checked':''}><span class="switch-art"></span><span><b>В Пекин вечерним рейсом</b><small>−9 663 ₸, но почти весь первый день уходит на дорогу.</small></span></label>`:'<div class="quiet-note">Семь ночей в отелях. Первую и последнюю ночь в аэропортах бюджет не превращает в гостиницу.</div>'}`;for(const [k,rule]of Object.entries({fx:[50,100,70],food:[300,1500,600],reserve:[0,100000,40000],air:[0,1000000,c.air]})){$('#'+k).oninput=e=>{if(e.target.value==='')return;state[k]=bounded(e.target.value,...rule);if(k==='fx')$('#fx-output').textContent=state.fx+' ₸';updateBudget();extras.forEach(e=>{const el=$('[data-extra-price="'+e.id+'"]');if(el)el.textContent='+'+money(e.cny*state.fx);});syncUrl();};$('#'+k).onchange=e=>e.target.value=state[k];}if($('#fast'))$('#fast').onchange=e=>{state.fast=e.target.checked;updateBudget();renderDay();renderTrains();renderJourney();syncUrl();};if($('#late'))$('#late').onchange=e=>{state.late=e.target.checked;state.air=null;renderControls();renderFlights();renderDay();renderCalendar();renderJourney();updateBudget();syncUrl();};}
function renderExtras(){$('#extras').innerHTML=extras.filter(e=>e.available.includes(state.route)).map(e=>`<label class="extra-option ${state.extras.includes(e.id)?'checked':''}"><input type="checkbox" value="${e.id}" ${state.extras.includes(e.id)?'checked':''}><span class="extra-check"></span><span><b>${e.title}</b><small>${e.detail}</small></span><strong data-extra-price="${e.id}">+${money(e.cny*state.fx)}</strong></label>`).join('');$$('.extra-option input').forEach(b=>b.onchange=()=>{state.extras=b.checked?[...new Set([...state.extras,b.value])]:state.extras.filter(x=>x!==b.value);b.closest('label').classList.toggle('checked',b.checked);updateBudget();syncUrl();});}
function updateBudget(){const c=calculate(),m=state.scope;updateBro(c);$$('[data-scope]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.scope)===m);b.setAttribute('aria-pressed',String(Number(b.dataset.scope)===m));});$('#budget-scope').textContent=m===1?'ПЛАН НА ЧЕЛОВЕКА':'ПЛАН НА ДВОИХ';$('#budget-total').textContent=money(c.total*m);$('#reserve-note').textContent='Включая '+money(state.reserve*m)+' резерва';$('#budget-status').textContent=c.left>=0?'В бюджете':'Выше лимита';$('#budget-status').classList.toggle('over',c.left<0);$('#meter-fill').style.width=Math.min(100,c.total/5000)+'%';$('#meter-fill').classList.toggle('over',c.left<0);$('#budget-left').innerHTML=`<span>${c.left>=0?'Ещё свободно':'Превышение'}</span><b class="${c.left<0?'negative':''}">${money(Math.abs(c.left)*m)}</b><small>Лимит ${money(500000*m)}</small>`;$('#breakdown').innerHTML=c.rows.map(([name,val,color])=>`<div><span><i class="dot ${color}"></i>${name}</span><b>${money(val*m)}</b></div>`).join('')+`<div class="reserve-line"><span>Резерв</span><b>${money(state.reserve*m)}</b></div>`;$('#spot-intercity').textContent=money(c.intercity);$('#spot-left').textContent=money(Math.abs(c.left));$('#spot-left-label').textContent=c.left>=0?'свободно до лимита':'сверх лимита';$('#spot-left').classList.toggle('negative',c.left<0);}
function flightCard(no,label,company,from,to,city1,city2,lines,price,priceLabel,key){return`<article class="flight-card"><div class="ticket-top"><span>${no} / ${label}</span><b>${company}</b></div><div class="airport-pair"><strong>${from}</strong><span class="flight-line">✈</span><strong>${to}</strong></div><p class="flight-cities">${city1}<span>${city2}</span></p><div class="flight-times">${lines.map(([a,b])=>`<p><b>${a}</b><span>${b}</span></p>`).join('')}</div><div class="ticket-bottom"><div><strong>${money(price)}</strong><small>${priceLabel}</small></div>${link('Проверить',key,'table-button')}</div></article>`;}
function renderFlights(){const r=routes[state.route],f={...r.internal};if(state.route==='B'&&state.late){f.time='16:55 — 20:45';f.price=63104;}$('#flights').innerHTML=flightCard('01','ТУДА-ОБРАТНО','FlyArystan','NQZ','URC','Астана','Урумчи',[['11 → 12 ноября','19:30 — 01:00'],['20 ноября, обратно','02:00 — 01:50']],73858,'оба направления / чел.','urc')+flightCard('02','ВГЛУБЬ КИТАЯ',f.airline,'URC',f.code,'Урумчи',f.to,[['12 ноября',f.time],['Прямой рейс','Отдельный билет']],f.price,'в одну сторону / чел.',f.source)+flightCard('03','ПЕРЕД ДОРОГОЙ ДОМОЙ','China Southern','CKG','URC','Чунцин','Урумчи',[['19 ноября','15:15 — 19:15'],['До следующего рейса','6 ч 45 мин']],54559,'в одну сторону / чел.','back');$('#layover-note').textContent=`В Урумчи туда: ${state.route==='B'&&state.late?'15 ч 55 мин':r.layover}. Обратно: 6 ч 45 мин. Въезд/выезд, регистрация и багаж заново. Автоматической защиты стыковки не предполагаем. Карточки показывают найденные цены, не изменённое вами число в калькуляторе.`;}
const table=(heads,rows)=>`<table class="data-table"><thead><tr>${heads.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
function renderTrains(){const ts=structuredClone(trains[state.route]);if(state.route==='A'&&state.fast)ts[0]=['13.11','Сиань-Северный → Лоян-Лунмэнь','西安北 → 洛阳龙门','G2022 · 18:07–19:47','164 CNY','xianTrain'];$('#train-table').innerHTML=table(['Дата','Станции','Текущий ориентир','Цена / чел.'],ts.map(([d,t,h,time,price,k])=>[d,`<b>${t}</b><small class="chinese">${h}</small>`,time,price+'<br>'+link('Расписание',k)]));}
function renderHotels(){$('#hotel-table').innerHTML=table(['Ноябрь','Город','Район','За двоих'],lodging[state.route].map(([d,c,a,p])=>[d,c,a,p+' CNY']));}
function renderCalendar(){const list=[['Сейчас','Выбрать вариант и проверить всю цепочку рейсов сразу на двоих.'],['После авиации',`Забронировать ${routes[state.route].hotelNights} ночей, настроить оплату и связь.`],...(state.route==='C'?[['31 октября','На 14 ноября: Чэнду — Чунцин.'],['1 ноября','На 15 ноября: Чунцин — Чжанцзяцзе.']]:[['30 октября',state.route==='A'?'На 13 ноября: Сиань — Лоян.':'На 13 ноября: ночной Пекин — Лоян.'],['1 ноября','На 15 ноября: Лоян — Иян, две полки.'],['2 ноября','На 16 ноября: Иян-Южный — Чжанцзяцзе.']]),['4 ноября',state.route==='C'?'На 18 ноября: Фужун туда-обратно и поезд в Чунцин.':'На 18 ноября: Чжанцзяцзе — Чунцин.'],...(state.route==='B'&&!state.late?[['5 ноября','Ориентир брони Запретного города на 12-е. Проверить правила музея.']]:[]),['Перед вылетом','Погода, слоты парков, канатки, регистрация и терминалы.']];$('#calendar').innerHTML=list.map(([d,t])=>`<div><span>${d}</span><p>${t}</p></div>`).join('')+'<p class="input-help">При горизонте 15 дней с учётом дня поездки. Часы открытия уточнять по станции в 12306.</p>';}
function renderPacking(){$('#packing').innerHTML=packing.map(([id,t,d])=>`<label class="packing-item"><input type="checkbox" data-check="${id}" ${state.checks[id]===true?'checked':''}><span><b>${t}</b><small>${d}</small></span></label>`).join('');$$('[data-check]').forEach(b=>b.onchange=()=>{state.checks[b.dataset.check]=b.checked;try{localStorage.setItem('china2026-checklist',JSON.stringify(state.checks));}catch{}checks();});checks();}
function checks(){$('#check-progress').textContent=packing.filter(([id])=>state.checks[id]===true).length+' из '+packing.length+' готово';}
const variants=[['A','Сиань',214852,452852,'Шаолинь и «Аватар», одна ночь в поезде. Без Стены.'],['A+','Скоростной поезд',221432,459432,'На 3 часа быстрее Сиань — Лоян, другие вокзалы.'],['B','Утренний Пекин',253334,484334,'Все три главные цели. Две ночи в поездах.'],['B-','Вечерний Пекин',243671,474671,'Стена остаётся, но первый день почти целиком в дороге.'],['C','Чэнду',237021,468021,'Панды, Чунцин и горы. Без ночных поездов, Стены и Шаолиня.']];
$('#comparison').innerHTML=table(['Вариант','Межгород / чел.','Вся поездка / чел.','Что меняется','Выбор'],[...variants.map(([id,n,inter,total,desc])=>[`<b>${id.replace('-','−')} · ${n}</b>`,money(inter),money(total),desc,`<button class="table-button" data-preset="${id}">Выбрать ${id.replace('-','−')}</button>`]),['<b>D · Синьцзян</b><small>Предварительный эскиз</small>','~125–145 тыс. ₸','Не рассчитана','Урумчи, Турфан, Кашгар. Другой тип поездки.','<button class="table-button" id="show-regional">Подробнее о D</button>']]);
function selectRoute(id){if(!routes[id])throw new Error('Выберите A, B или C');state.route=id;state.air=null;state.day=12;state.extras=state.extras.filter(x=>extras.some(e=>e.id===x&&e.available.includes(id)));renderAll();syncUrl();}
function renderAll(){renderSpotlight();renderJourney();renderDay();renderControls();renderExtras();renderFlights();renderTrains();renderHotels();renderCalendar();updateBudget();}
function reset(){state.fx=70;state.food=600;state.reserve=40000;state.air=null;state.fast=false;state.late=false;state.extras=[];renderAll();syncUrl();toast('Исходный расчёт восстановлен');}
async function share(){syncUrl();try{await navigator.clipboard.writeText(location.href);toast('Ссылка с вашим вариантом скопирована');}catch{const d=document.createElement('dialog');d.className='share-dialog';d.innerHTML='<h3>Ссылка на ваш вариант</h3><p>Выделите и скопируйте адрес:</p><input aria-label="Ссылка на выбранный вариант" readonly><button class="button">Готово</button>';d.querySelector('input').value=location.href;d.querySelector('button').onclick=()=>{d.close();d.remove();};d.oncancel=()=>d.remove();document.body.append(d);d.showModal();d.querySelector('input').select();}}
$$('[data-route]').forEach(b=>b.onclick=()=>selectRoute(b.dataset.route));$$('[data-scope]').forEach(b=>b.onclick=()=>{state.scope=Number(b.dataset.scope);updateBudget();syncUrl();});$$('[data-preset]').forEach(b=>b.onclick=()=>{const v=b.dataset.preset;state.fast=v==='A+';state.late=v==='B-';state.fx=70;state.food=600;state.reserve=40000;state.extras=[];selectRoute(v[0]);$('#routes').scrollIntoView();toast('Выбран вариант '+v.replace('-','−'));});
['share-top','share-budget','share-bottom'].forEach(id=>$('#'+id).onclick=share);$('#reset-budget').onclick=reset;$('#show-regional').onclick=()=>$('#regional').showModal();$$('.dialog-close,.dialog-done').forEach(b=>b.onclick=()=>$('#regional').close());$('#regional').onclick=e=>{if(e.target===$('#regional')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}};
renderAll();renderPacking();

// Optional agent interface: same local state, no booking or network side effects.
const context=document.modelContext;
if(context?.registerTool){const life=new AbortController();const snapshot=()=>({route:state.route,fx:state.fx,fast:state.fast,late:state.late,totalPerPerson:calculate().total,leftPerPerson:calculate().left});const register=t=>{try{Promise.resolve(context.registerTool(t,{signal:life.signal})).catch(()=>{});}catch{}};register({name:'read_china_trip',description:'Read the selected route and budget. Does not book anything.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>snapshot()});register({name:'configure_china_route',description:'Change this page to route A, B or C and optional variant. No booking or purchase.',inputSchema:{type:'object',properties:{route:{type:'string',enum:['A','B','C']},variant:{type:'string',enum:['standard','fast_train','evening_flight']}},required:['route'],additionalProperties:false},annotations:{readOnlyHint:false},execute:i=>{if(!i||!routes[i.route]||!['standard','fast_train','evening_flight',undefined].includes(i.variant)||(i.variant==='fast_train'&&i.route!=='A')||(i.variant==='evening_flight'&&i.route!=='B'))throw new Error('Unsupported route or variant');state.fast=i.variant==='fast_train';state.late=i.variant==='evening_flight';selectRoute(i.route);return snapshot();}});window.addEventListener('pagehide',()=>life.abort(),{once:true});}
