import {routes,transport,getPlan,extras,sources,packing,credits,checkedAt} from './data.js';
import {mountJourneyAnimation} from './journey-animation.js';
const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)];
const money=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(Math.round(n))+' ₸';
const ext=(text,url)=>`<a class="text-link" href="${url}" target="_blank" rel="noopener noreferrer">${text}</a>`;
const link=(text,key)=>ext(text,sources[key]);
const date=(iso,format={day:'numeric',month:'long'})=>new Date(iso+'T12:00:00').toLocaleDateString('ru-RU',format);
const bound=(v,min,max,f)=>v!==null&&v!==''&&Number.isFinite(Number(v))?Math.max(min,Math.min(max,Number(v))):f;
const query=new URLSearchParams(location.search);
// Older shared links used total airfare; do not reinterpret it as domestic airfare.
if(query.get('v')!=='2'){query.delete('air');query.delete('paid');query.delete('nights');}
const state={route:routes[query.get('r')]?query.get('r'):'B',choice:query.get('t')||'split',day:0,scope:query.get('scope')==='2'?2:1,fx:bound(query.get('fx'),50,100,70),room:bound(query.get('room'),80,600,160),food:bound(query.get('food'),30,250,80),reserve:bound(query.get('reserve'),0,150000,30000),paid:query.has('paid')?bound(query.get('paid'),0,1000000,null):null,nights:query.has('nights')?bound(query.get('nights'),0,12,null):null,air:query.has('air')?bound(query.get('air'),0,1000000,null):null,extras:(query.get('extras')||'').split(',').filter(id=>extras.some(e=>e.id===id&&e.available.includes(query.get('r')||'B'))),checks:{}};
if(!transport[state.route].some(t=>t.id===state.choice))state.choice=transport[state.route][0].id;
if(state.extras.includes('bungee'))state.extras=state.extras.filter(id=>id!=='bridge');if(state.route==='B'&&state.extras.includes('qianxi'))state.extras=state.extras.filter(id=>id!=='wulong');
try{const c=JSON.parse(localStorage.getItem('china2026-late-checklist')||'{}');if(c&&typeof c==='object'&&!Array.isArray(c))state.checks=c;}catch{}
const month=iso=>date(iso).replace(/^\d+\s+/, '');
const selected=()=>transport[state.route].find(t=>t.id===state.choice);
const plan=()=>getPlan(state.route,state.choice);
function calculate(s=state){const r=routes[s.route],t=transport[s.route].find(t=>t.id===s.choice),air=s.air??t.air,nights=s.nights??t.nights;
 const rows=[['Новые внутренние перелёты',air,'lime'],['Поезда',r.rail*s.fx,'purple'],[`Жильё · ${nights} ночей`,s.room*nights/2*s.fx,'blue'],[`Еда · ${t.foodDays} дней`,s.food*t.foodDays*s.fx,'orange'],['Входы и развлечения',r.entry*s.fx,'mint'],['Местный транспорт',r.local*s.fx,'gray'],['Связь и страховка',12000,'gray'],['Аэропорт Астаны',4000,'gray']];
 const active=extras.filter(e=>s.extras.includes(e.id)&&e.available.includes(s.route));if(active.length)rows.push(['Дополнительные впечатления',active.reduce((n,e)=>n+e.cny*s.fx,0),'orange']);
 const additional=rows.reduce((n,r)=>n+r[1],0)+s.reserve;if(s.paid!==null)rows.unshift(['Уже оплачено · Астана ↔ Урумчи',s.paid,'lime']);
 const total=additional+(s.paid??0);return{air,rows,total,additional,known:s.paid!==null,left:500000-total,active};}
function sync(){const q=new URLSearchParams({v:'2',r:state.route,t:state.choice});for(const [key,v]of Object.entries({scope:1,fx:70,room:160,food:80,reserve:30000}))if(state[key]!==v)q.set(key,state[key]);if(state.air!==null)q.set('air',state.air);if(state.paid!==null)q.set('paid',state.paid);if(state.nights!==null)q.set('nights',state.nights);if(state.extras.length)q.set('extras',state.extras.join(','));history.replaceState(null,'',location.pathname+'?'+q+location.hash);}
let toastTimer;function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
async function share(){sync();try{await navigator.clipboard.writeText(location.href);toast('Ссылка с вашим выбором скопирована');}catch{const dialog=$('#share-dialog');$('#share-url').value=location.href;dialog.showModal();$('#share-url').select();}}
const heading=(n,t,aside='')=>`<div class="section-heading"><div><p class="eyebrow">${n}</p><h2>${t}</h2></div>${aside?`<p>${aside}</p>`:''}</div>`;
const details=(title,body)=>`<details class="accordion"><summary>${title}<span class="plus">+</span></summary><div class="details-body">${body}</div></details>`;
const table=(heads,rows)=>`<table class="data-table"><thead><tr>${heads.map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
$('#planner-content').innerHTML=`
<section class="departure-deal"><div><p class="eyebrow">БИЛЕТЫ УЖЕ КУПЛЕНЫ · МАРШРУТ ПЕРЕСОБРАН</p><h3>21 ноября → 1 декабря.</h3><p>Астана ↔ Урумчи. Прилёт <b>ночью 22 ноября</b>; вылет домой <b>1 декабря в 02:00</b>. В аэропорту вечером 30-го. Внутри Китая — две основные туристические базы; Урумчи в дальних вариантах остаётся транзитом.</p></div><div><b>22–30 ноября</b><small>9 дат для прогулок и дороги. Точный час прилёта ещё сверить; первый внутренний рейс — 23-го. Если прилёт рано утром 22-го, можно искать вылет днём 22-го ради дополнительного дня, но этот тариф не проверен.</small></div></section>
<section class="block compact-block" id="transport">${heading('02 / ВЫБИРАЕМ ДОРОГУ','Теперь сравниваем только Китай.')}<div id="transport-options" class="transport-options" role="group" aria-label="Вариант перелётов"></div><div id="transport-note" class="travel-note"></div></section>
<section id="journey-section" class="journey-section"><div class="minor-heading"><h3>Как движемся</h3><span class="meta">Самолёты, поезда и прогулки · нажмите ▶</span></div><div id="trip-animation" class="trip-animation"></div><div id="inclusions" class="inclusions"></div></section>
<section id="days" class="block">${heading('03 / НЕ ГАЛОЧКИ, А ПРОГУЛКИ','Два города, длинные вечера.','21 ноября — 1 декабря.<br>Все часы местные.')}<div id="day-tabs" class="day-tabs" role="tablist" aria-label="Дни поездки"></div><article id="day-panel" class="day-panel" role="tabpanel" tabindex="0"></article>${details('Весь маршрут на одной странице','<div id="all-days"></div>')}</section>
<section id="baths" class="block">${heading('04 / ТО САМОЕ «ВСЁ ВКЛЮЧЕНО»','Баня, еда. И можно остаться спать.','Один вечер ради опыта.<br>Пакеты бывают разными.')}<p class="meta">Даты ниже — для пары B Чэнду + Чунцин. В паре A баню в Чунцине ставить вечером 24-го с учётом поезда 25-го; для Урумчи + Турфана эти заведения не подходят.</p><p class="muted">Ищите 汤泉 или 洗浴中心. Ночёвка часто означает общее кресло / лежак; отдельная комната и массаж могут стоить дополнительно. Это не автоматическая замена отелю.</p>
<div class="spa-grid"><article class="spa-card"><p class="eyebrow">ЧЭНДУ · ОПЦИЯ 24 → 25 НОЯБРЯ</p><h3>FUFU <span>浮浮汤</span></h3><p class="spa-price">US$68 <small>/ человек · пакет посредника</small></p><p>18 часов: ванны, сауны, еда в четыре периода и общий ночной отдых. Оригинал паспорта обязателен. Массаж и отдельные комнаты оплачиваются дополнительно.</p><p class="meta">Вход около 18:00 → выход до 12:00 следующего дня, часы питания проверить. Это опубликованный пакет PandaStroll, не подтверждённая цена у двери.</p><p class="chinese">浮浮汤温泉生活馆（炎华置信花千集店）</p>${link('Пакет и условия','fufu')}</article>
<article class="spa-card"><p class="eyebrow">ЧУНЦИН · ОПЦИЯ 27 → 28 НОЯБРЯ</p><h3>Qianxi <span>浅溪汤泉</span></h3><p class="spa-price">339 CNY <small>/ человек · ~23 730 ₸ при курсе 70</small></p><p>Опубликован пакет 16 часов с ночёвкой, фруктами, напитками, перекусами и <b>одним</b> шведским столом. 24 часа + один шведский стол — 389 CNY.</p><p class="meta">Например 18:00 → 10:00. Приём паспорта Казахстана и конкретный филиал для ночёвки пока не подтверждены. Не отменять отель до подтверждения.</p>${link('Тарифы продавца Hugh Chongqing','qianxi')}</article></div>
${details('Что проверить и как не переплатить','<p>Попросите итоговую цену с ночной доплатой, часы входа/выхода, число включённых приёмов пищи и место для сна. Игры, процедуры и отдельные комнаты могут быть платными. Вещи на хранение — по правилам заведения; нужны сланцы по доступности, сменное бельё и оригиналы паспортов. Банные зоны обычно разделены по полу.</p><p>При номере 160 CNY на двоих ваша доля 80 CNY: баня за 339 CNY выгодна как впечатление с едой, но дороже простой ночёвки. В калькуляторе она добавляется к полной смете. Уменьшите ночи на одну только после подтверждения сна; расходы на питание автоматически не вычитаются.</p><p>Для Урумчи не найден достаточно подтверждённый пакет с современной ценой и ночёвкой для иностранцев. После ночного прилёта используем подтверждённый отель.</p>')}
${details('Показать сотруднику: вопрос по-китайски','<p class="chinese">我们是两位哈萨克斯坦游客，持哈萨克斯坦护照。可以用护照登记并过夜吗？套餐包含几小时、哪些餐食和过夜费？休息区需要预约吗？超时怎么收费？</p><p>Мы два туриста из Казахстана. Можно зарегистрироваться и ночевать по нашим паспортам? Сколько часов, какие блюда и ночные сборы включены? Нужно бронировать место отдыха? Как оплачивается превышение времени?</p>')}
</section>
<section id="budget" class="block">${heading('05 / ВАШИ 500 ТЫСЯЧ','Оплачено. И сколько ещё потратить.')}<div class="segmented" role="group" aria-label="Показывать бюджет"><button data-scope="1">На одного</button><button data-scope="2">На двоих</button></div><div class="budget-layout"><div class="budget-editor"><div id="budget-controls"></div><div class="extras-heading"><h3>Добавим впечатлений?</h3><p>Дополнения требуют времени в программе. Суммы — на человека.</p></div><div id="extras" class="extras"></div></div><aside class="budget-result"><div class="budget-result-top"><span id="budget-scope"></span><span id="budget-status" class="budget-badge"></span></div><div id="budget-total" class="budget-total" aria-live="polite"></div><p id="reserve-note"></p><div class="budget-meter"><span id="meter-fill"></span></div><div id="budget-left" class="budget-left"></div><div id="breakdown" class="budget-breakdown"></div><div class="budget-bro"><img src="assets/friend-sticker.png" alt="" width="72" height="80" loading="lazy"><p id="budget-bro-quote"></p></div><p class="budget-disclaimer">Пока цена купленных международных билетов не указана, показаны дополнительные расходы. Жильё, еда, развлечения и дороги — плановые лимиты. 9 ночей: 8 по маршруту + запас на короткую ночь при раннем прилёте 22-го. При позднем прилёте поставьте 8.</p><button class="button wide" id="share-budget">Отправить этот вариант другу</button><button class="reset-button" id="reset-budget">Вернуть исходную смету</button></aside></div></section>
<section id="tickets" class="block">${heading('06 / ПОЛНАЯ ЦЕПОЧКА','Купленные и будущие билеты.','Новые тарифы замечены 10 октября.<br>Суммы на человека.')}<div id="flights" class="flight-grid"></div><div id="layover-note" class="travel-note"></div>${details('Поезда: время и правильные вокзалы','<p>Ориентиры по текущим расписаниям; ноябрьские места ещё не продаются. Окно 12306 — 15 дней с учётом отправления. Предзаказ посредника не гарантирует билет.</p><div id="train-table" class="table-scroll"></div>'+link('Правило 12306','railWindow'))}${details('Жильё: районы и даты','<p>Цель: 160 CNY за номер на двоих с двумя кроватями, то есть 80 CNY каждому. Это смета, конкретное наличие не проверено. Нужны отопление, оформление иностранных гостей и подтверждённый час заезда.</p><div id="hotel-table" class="table-scroll"></div><p class="meta">Таблица показывает 8 основных ночей. При прилёте рано 22-го нужна ещё ночь 21→22 или согласованный ранний заезд; смета включает её как запас. Если прилетаете поздно 22-го, первый отель 22→23.</p>')}</section>
<section id="compare" class="block">${heading('07 / БЛИЖЕ ИЛИ ИНТЕРЕСНЕЕ','Выбираем впечатления, а не километры.')}<div id="comparison" class="comparison-scroll"></div>
${details('Какие города рядом с Урумчи и зачем туда ехать',`<div class="table-scroll">${table(['Направление','Дорога после Урумчи','Что получите','Мой вывод'],[
 ['Турфан','~1 час скоростным поездом + трансфер','Цзяохэ, кяризы, история Шёлкового пути','Ближе и дешевле всего. Зимой спокойнее.'],
 ['Сиань + Лоян','~3 ч 15–35 мин самолётом до Сианя; дальше поезд','Терракотовая армия, Лунмэнь, Шаолинь выездом','Если монахи важнее неона. Свежая полная авиапара не подтверждена; цену не подставляем.'],
 ['Чэнду + Чунцин','3 ч 35 мин самолётом; ~2 часа поездом','Панды, хотпот, чайные, городские виды и бани','Лучше подходит вашим вечерам и развлечениям.'],
 ['Чунцин + Чжанцзяцзе','3 ч 50 мин самолётом; ~2,5–3 часа поездом','Неон, «Аватар», высотные дорожки по погоде','Больше природы, дороже и чувствительнее к туману.'],
 ['Пекин + соседний город','Дальний отдельный перелёт из Урумчи','Великая стена и столица','Имеет смысл ради Стены; новая авиапара не проверена. Не добавлять к двум другим городам.']
 ])}</div><p>Время полёта не включает аэропорты. Внутренние рейсы тоже требуют отдельной регистрации. Близость не делает направление лучшим для вашей цели.</p>`)}
${details('Поезд вместо самолёта: где экономия настоящая',`<p>На Турфан поезд — лучший выбор: скоростной около часа, 51,5 CNY. В текущей выдаче есть обычные поезда около 1,5–2 часов за 24,5 CNY; экономия примерно 1 900 ₸ в одну сторону. На поездке в 9 дней это необязательно стоит дополнительного времени. ${link('Текущий список','turpanTrain')}</p><p>В центральный Китай расстояния совсем другие: до Сианя поезд занимает существенную часть дня или ночь и следующий день. Сравнивать нужно спальное место, еду и потерянный день, а не только сидячий тариф. Для Чэнду и Чунцина при найденной авиации 119–136 тысяч туда-обратно я выбираю самолёт. ${link('Посмотреть Урумчи → Сиань','urcTrain')}</p><p>Возврат в Урумчи самолётом 29 ноября даёт дополнительный день запаса перед международным вылетом. Это самый спокойный вариант; его тариф не проверен и не включён в показанные авиапары.</p>`)}
</section>
<section id="prepare" class="block">${heading('08 / ПЕРЕД ВЫЛЕТОМ','Собрать рюкзак. И настроить Китай.')}<div class="prepare-grid"><div><div class="minor-heading"><h3>Личный чек-лист</h3><span class="meta" id="check-progress"></span></div><p class="meta">Сохраняется в этом браузере. У друга свой список.</p><div id="packing"></div></div><div><h3>Когда покупать</h3><div id="calendar" class="calendar"></div></div></div><div class="practical-grid">
${details('Паспорт, въезд и отели',`<p>Гражданам Казахстана с обычными паспортами туристический въезд по соглашению без визы: до 30 дней за один въезд и до 90 за 180 дней. ${link('МИД Казахстана','visa')}</p><p>Обратный билет, адрес первого отеля на китайском, страховку и копию паспорта сохранить офлайн. Отель оформляет регистрацию проживания. Проверить действующие правила перед поездкой. ${link('Форма NIA','arrival')}</p>`)}
${details('Багаж, интернет и деньги',`<p>Ваш международный перевозчик и купленный багаж пока не известны — смотреть билет, не старую смету. Для найденной пары Чэнду: 8 кг ручная кладь + 20 кг багажа. Для пары Чунцин: 5 кг ручная туда / 8 кг обратно, багаж 20 кг. Перед оплатой сверить каждый участок.</p><p>Внутри Китая power bank нужен с читаемой маркировкой CCC/3C и без отзыва серии; перевозится в ручной клади. ${link('Правило CAAC','power')}</p><p>Настроить Alipay, проверить оплату своей картой / Kaspi; взять резервную карту и наличные CNY. ${link('Kaspi Alipay+','kaspi')}</p><p>Туристическая eSIM с нужным покрытием и доступом к приложениям; проверить телефон. Переводчик с китайским офлайн, карты и адреса отелей сохранить заранее. 12 000 ₸ на связь и страховку — лимит, не найденный пакет. В Китае нет привычного доступа ко всем зарубежным сервисам; изучить условия eSIM, не обещать себе работу любого приложения.</p>`)}
${details('Зима, погода и экстрим',`<p>Урумчи и Турфан — зимняя одежда, шапка и перчатки; Чэнду и Чунцин — слои и защита от сырости; горы — нескользящая обувь. Конкретного прогноза ещё нет. Проверить за 5–7 дней и затем перед горным выездом.</p><p>В Чунцине приключение — городские уровни, канатная дорога и Улон. Банджи — только в варианте Чжанцзяцзе: оператор публикует 1 998 CNY + 178 вход, 16–65 лет, 40–90 кг. Уточнить погоду и страховое покрытие. ${link('Оператор','bungee')}</p><p>Тяньмэнь и зимние лыжные склоны нельзя обещать открытыми к вашей дате. ${link('Объявление о реконструкции','tianmen')}</p><p>В Синьцзяне авиация/поезда используют Пекинское время UTC+8. В разговоре могут назвать время UTC+6: уточняйте 北京时间. Все часы этого плана — по официальному китайскому времени.</p>`)}
</div></section>
<section class="final-card"><div><p class="eyebrow">ГОТОВО ДЛЯ ОБСУЖДЕНИЯ ВДВОЁМ</p><h2>Куплены билеты. Выбираем Китай.</h2><p>Мой выбор — Чэнду + Чунцин. Урумчи + Турфан — для минимальных расходов. Чунцин + Чжанцзяцзе — ради гор. Стоимость уже купленной авиации добавьте в калькулятор.</p></div><div><button class="button" id="share-final">Скопировать наш выбор ↗</button><a class="pdf-link" href="guide-21-november.md" download>Скачать руководство</a><button class="reset-button" id="print-plan">Распечатать этот маршрут</button></div></section>
${details('Источники, цены и фотографии',`<p>Проверено ${checkedAt}. Новые авиапары на двух взрослых; суммы на человека, без оплаты. Расчётный курс 70 ₸/CNY — допущение для сметы, не текущий банковский курс. Жильё и местные расходы — лимиты; поезда пока ориентиры. Банные пакеты опубликованы продавцами, не подтверждены самим заведением на выбранную дату.</p><div class="source-links">${[['Урумчи ↔ Чэнду','chengdu'],['Урумчи ↔ Чунцин','domestic'],['Чэнду ↔ Чунцин поезд','chengduTrain'],['Чунцин ↔ Чжанцзяцзе','chongTrain'],['Урумчи ↔ Турфан','turpanTrain'],['База панд','panda'],['Парк Чжанцзяцзе','park'],['FUFU','fufu'],['Qianxi','qianxi'],['Кяризы','turpan'],['Цзяохэ','jiaohe'],['Тяньчи','tianchi'],['Сиань: расписание самолётов','xian'],['НБК','fx']].map(([t,k])=>link(t,k)).join('')}</div>${credits.map(c=>`<p class="credit">${c.name} · ${c.author}: ${ext('источник',c.url)} · ${ext(c.license,c.licenseUrl)}</p>`).join('')}<p class="credit">Стикер друга добавлен по вашей просьбе; реплики шуточные.</p>`)}
<dialog id="share-dialog" class="share-dialog"><button class="dialog-close" aria-label="Закрыть">×</button><h2>Ваш вариант — одной ссылкой</h2><p>Скопируйте ссылку: она сохраняет маршрут и смету. Изменения не синхронизируются автоматически между вами. Указанная цена купленных билетов тоже войдёт в ссылку.</p><input id="share-url" readonly aria-label="Ссылка на выбранный маршрут"></dialog>`;
function renderSpotlight(){const r=routes[state.route],t=selected(),c=calculate();$('#route-choices').innerHTML=Object.entries(routes).map(([key,r])=>{const total=calculate({...state,route:key,choice:transport[key][0].id,air:null,paid:null,nights:null,extras:[],fx:70,room:160,food:80,reserve:30000}).total;return`<button type="button" class="route-choice ${key===state.route?'selected':''}" data-route="${key}" aria-pressed="${key===state.route}"><span class="route-letter">${key}</span><span class="route-label"><b>${r.name}</b><small>${r.tag}</small></span><span class="route-price">~${money(total)}<small>ещё потратить / чел.</small></span></button>`;}).join('');
 $('#route-spotlight').innerHTML=`<div class="spotlight-copy"><p class="eyebrow">МАРШРУТ ${state.route} / ${r.tag}</p><h3>${r.title}</h3><p>${r.description}</p><div class="quick-stats"><span><b id="spot-air">${money(c.air)}</b>новые рейсы / чел.</span><span><b>22–30 ноября</b>${t.span}</span><span><b id="spot-left">${money(Math.abs(c.left))}</b><span id="spot-left-label">${c.left>=0?'до учёта купленных билетов':'сверх лимита'}</span></span></div></div><div class="spotlight-visual">${state.route==='D'?'<div class="city-poster"><span>乌鲁木齐</span><span>吐鲁番</span><small>УРУМЧИ × ТУРФАН</small><div class="poster-wall" aria-hidden="true">▥ ▥ ▥ ▥ ▥</div></div>':`<img src="assets/${r.image}" alt="${r.place}" width="1280" height="853">`}<div class="photo-caption"><span>${state.route==='D'?'丝绸之路':r.han}</span><strong>${state.route==='D'?'Шёлковый путь':r.place}</strong><small>${state.route==='D'?'Графическая иллюстрация, не фотография города.':r.caption}</small></div></div>`;
 $$('[data-route]').forEach(b=>b.onclick=()=>{state.route=b.dataset.route;state.choice=transport[state.route][0].id;state.air=null;state.nights=null;state.day=0;state.extras=state.extras.filter(id=>extras.some(e=>e.id===id&&e.available.includes(state.route)));renderRoute();sync();});$('#crew-quote').textContent=r.quote;}
function renderTransport(){$('#transport-options').innerHTML=transport[state.route].map(t=>`<button class="transport-choice ${t.id===state.choice?'selected':''}" data-transport="${t.id}" aria-pressed="${t.id===state.choice}"><span>${t.label}</span><b>${money(t.air)}</b><small>новые рейсы / чел. · ${t.days} дней</small></button>`).join('');$('#transport-note').innerHTML=`<span class="note-symbol">i</span><div><b>${selected().span} · ${selected().days} календарных дней</b><p>${selected().detail}</p></div>`;$$('[data-transport]').forEach(b=>b.onclick=()=>{state.choice=b.dataset.transport;state.air=null;state.nights=null;state.day=0;renderRoute();sync();});}
function renderJourney(){const days=plan();$('#inclusions').innerHTML=`<div>${routes[state.route].included.map(t=>`<span class="included">✓ ${t}</span>`).join('')}</div><p>${routes[state.route].missed}</p>`;mountJourneyAnimation({route:state.route,span:selected().span,scenes:days.map(d=>({...d,detail:d.steps.map(([t,p])=>p).join(' ')})),onDay:iso=>{const i=days.findIndex(d=>d.date===iso);if(i>=0){state.day=i;renderDay();}}});}
function renderDay(){const days=plan();state.day=Math.min(state.day,days.length-1);const d=days[state.day];$('#day-tabs').style.setProperty('--day-count',days.length);$('#day-tabs').innerHTML=days.map((d,i)=>`<button class="day-tab ${i===state.day?'active':''}" role="tab" id="day-${i}" data-day="${i}" aria-controls="day-panel" aria-selected="${i===state.day}" tabindex="${i===state.day?0:-1}"><span>День ${i+1}</span><b>${Number(d.date.slice(8))}</b><small>${month(d.date)}</small></button>`).join('');$('#day-panel').setAttribute('aria-labelledby','day-'+state.day);$('#day-panel').innerHTML=`<div class="day-heading"><span class="day-big">${Number(d.date.slice(8))}<small>${month(d.date).toUpperCase()}</small></span><span class="day-city">${d.city}</span><div class="night-label"><span>ГДЕ СПИМ</span><b>${d.sleep}</b></div></div><div class="day-story"><h3>${d.title}</h3><div class="day-steps">${d.steps.map(([time,text])=>`<div><span>${time}</span><p>${text}</p></div>`).join('')}</div><div class="day-tip"><b>На заметку</b><p>${d.tip}</p></div></div>`;
 $('#all-days').innerHTML=days.map((d,i)=>`<article class="full-day"><button class="compact-day" data-jump="${i}"><span>${date(d.date,{day:'2-digit',month:'2-digit'})}</span><b>${d.title}</b><small>${d.sleep}</small></button><div class="full-day-detail">${d.steps.map(([t,p])=>`<p><b>${t}</b> — ${p}</p>`).join('')}<p class="meta">${d.tip}</p></div></article>`).join('');
 $$('[data-day]').forEach(b=>{b.onclick=()=>{state.day=Number(b.dataset.day);renderDay();$('#day-'+state.day).focus({preventScroll:true});};b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();state.day=e.key==='Home'?0:e.key==='End'?days.length-1:Math.max(0,Math.min(days.length-1,state.day+(e.key==='ArrowRight'?1:-1)));renderDay();$('#day-'+state.day).focus();};});$$('[data-jump]').forEach(b=>b.onclick=()=>{state.day=Number(b.dataset.jump);renderDay();$('#days').scrollIntoView();});}
function renderControls(){const t=selected();$('#budget-controls').innerHTML=`<h3>Настройте под себя</h3><p class="muted">Цена номера — за двоих. Все прочие суммы на человека.</p><div class="control-group"><label for="paid">Уже оплачено: Астана ↔ Урумчи / чел., ₸</label><input id="paid" type="number" min="0" max="1000000" inputmode="numeric" placeholder="Цена пока не указана" value="${state.paid??''}"><p class="input-help">Пустое поле означает неизвестную цену. После ввода появится полная смета и остаток до 500 000 ₸. Цена войдёт в ссылку «Поделиться».</p></div><div class="control-group"><label for="fx">Расчётный курс юаня <output id="fx-output">${state.fx} ₸</output></label><input id="fx" type="range" min="50" max="100" value="${state.fx}"><p class="input-help">70 ₸ — допущение для планирования, не актуальный курс обменника.</p></div><div class="control-pair"><div><label for="room">Номер на двоих / ночь, CNY</label><input id="room" type="number" min="80" max="600" value="${state.room}"></div><div><label for="nights">Оплачиваемых ночей</label><input id="nights" type="number" min="0" max="12" step="1" value="${state.nights??t.nights}"><p class="input-help">8 основных + 1 запасная короткая. 8 при позднем прилёте. Минус ночь бани только после подтверждения.</p></div></div><div class="control-pair"><div><label for="food">Еда / день / человек, CNY</label><input id="food" type="number" min="30" max="250" value="${state.food}"><p class="input-help">${t.foodDays} дней: 22–30 ноября, с запасом на день прилёта.</p></div><div><label for="reserve">Резерв / человек, ₸</label><input id="reserve" type="number" min="0" max="150000" step="5000" value="${state.reserve}"></div></div><div class="control-group"><label for="air">Новые внутренние рейсы / человек, ₸</label><input id="air" type="number" min="0" max="1000000" value="${calculate().air}"><p class="input-help">${state.route==='D'?'В этом варианте новых самолётов нет.':'Подставьте окончательную сумму с багажом и комиссией. Международные билеты в поле выше.'}</p></div><p class="quiet-note">Входы: ${routes[state.route].entry} CNY. Местные дороги: ${routes[state.route].local} CNY. Это лимиты, конкретные брони ещё не сделаны.</p>`;
 for(const [key,rules]of Object.entries({fx:[50,100,70],room:[80,600,160],nights:[0,12,t.nights],food:[30,250,80],reserve:[0,150000,30000],air:[0,1000000,t.air],paid:[0,1000000,null]})){$('#'+key).oninput=e=>{if(key==='paid'&&e.target.value==='')state.paid=null;else{if(!e.target.value)return;state[key]=bound(e.target.value,...rules);if(key==='nights')state[key]=Math.round(state[key]);}$('#fx-output').textContent=state.fx+' ₸';renderExtras();updateBudget();if(key==='paid')renderFlights();sync();};$('#'+key).onchange=e=>{if(state[key]!==null)e.target.value=state[key];};}}
function renderExtras(){$('#extras').innerHTML=extras.filter(e=>e.available.includes(state.route)).map(e=>`<label class="extra-option ${state.extras.includes(e.id)?'checked':''}"><input type="checkbox" value="${e.id}" ${state.extras.includes(e.id)?'checked':''}><span class="extra-check"></span><span><b>${e.title}</b><small>${e.detail}</small></span><strong>+${money(e.cny*state.fx)}</strong></label>`).join('');$$('.extra-option input').forEach(b=>b.onchange=()=>{state.extras=state.extras.filter(id=>id!==b.value);if(b.checked){if(b.value==='bridge')state.extras=state.extras.filter(id=>id!=='bungee');if(b.value==='bungee')state.extras=state.extras.filter(id=>id!=='bridge');if(state.route==='B'&&b.value==='wulong')state.extras=state.extras.filter(id=>id!=='qianxi');if(state.route==='B'&&b.value==='qianxi')state.extras=state.extras.filter(id=>id!=='wulong');state.extras.push(b.value);}renderExtras();updateBudget();sync();});}
function updateBudget(){const c=calculate(),m=state.scope;$$('[data-scope]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.scope)===m);b.setAttribute('aria-pressed',String(Number(b.dataset.scope)===m));});$('#budget-scope').textContent=(m===1?'НА ЧЕЛОВЕКА':'НА ДВОИХ')+(c.known?' · ВСЯ ПОЕЗДКА':' · ЕЩЁ ПОТРАТИТЬ');$('#budget-total').textContent=money(c.total*m);$('#reserve-note').textContent='Включая '+money(state.reserve*m)+' резерва'+(c.known?' и купленные билеты.':'. Купленные билеты ещё не учтены.');$('#budget-status').textContent=c.known?(c.left>=0?'В бюджете':'Выше лимита'):'Цена билетов неизвестна';$('#budget-status').classList.toggle('over',c.left<0);$('#meter-fill').style.width=Math.min(100,c.total/5000)+'%';$('#meter-fill').classList.toggle('over',c.left<0);$('#budget-left').innerHTML=c.known?`<span>${c.left>=0?'Ещё свободно':'Превышение'}</span><b class="${c.left<0?'negative':''}">${money(Math.abs(c.left)*m)}</b><small>Лимит ${money(500000*m)}</small>`:`<span>Чтобы вся поездка уложилась в лимит</span><b>${c.left>=0?'купленные билеты ≤ '+money(c.left*m):'дополнительные расходы уже выше лимита'}</b><small>Это порог цены билетов, не свободный остаток. Лимит ${money(500000*m)}.</small>`;$('#breakdown').innerHTML=c.rows.map(([label,n,color])=>`<div><span><i class="dot ${color}"></i>${label}</span><b>${money(n*m)}</b></div>`).join('')+`<div class="reserve-line"><span>Резерв</span><b>${money(state.reserve*m)}</b></div>`;$('#spot-air').textContent=money(c.air);$('#spot-left').textContent=money(c.known?Math.abs(c.left):c.additional);$('#spot-left').classList.toggle('negative',c.known&&c.left<0);$('#spot-left-label').textContent=c.known?(c.left>=0?'свободно до лимита':'сверх лимита'):'ещё потратить / чел.';$('#budget-bro-quote').textContent=!c.known?'Бро, впиши купленные билеты. Тогда поймём, сколько осталось на баню.':c.left<0?'Бро, приключение крутое, но лимит уже превысили.':'На лапшу и приключения остаётся. Одобряю.';}
function flightCard(no,label,company,from,to,lines,price,key){return`<article class="flight-card"><div class="ticket-top"><span>${no} / ${label}</span><b>${company}</b></div><div class="airport-pair"><strong>${from}</strong><span class="flight-line">✈</span><strong>${to}</strong></div><div class="flight-times">${lines.map(([a,b])=>`<p><b>${a}</b><span>${b}</span></p>`).join('')}</div><div class="ticket-bottom"><div><strong>${money(price)}</strong><small>туда-обратно / человек</small></div>${link('Проверить тариф',key)}</div></article>`;}
function renderFlights(){const t=selected();$('#flights').innerHTML=`<article class="flight-card"><div class="ticket-top"><span>01 / УЖЕ КУПЛЕНЫ</span><b>Ваш международный билет</b></div><div class="airport-pair"><strong>NQZ</strong><span class="flight-line">✈</span><strong>URC</strong></div><div class="flight-times"><p><b>21 → 22 ноября</b><span>Вылет → ночной прилёт</span></p><p><b>1 декабря · 02:00</b><span>Вылет домой из Урумчи</span></p><p><b>Перевозчик / багаж</b><span>Сверить с вашим билетом</span></p></div><div class="ticket-bottom"><div><strong>${state.paid===null?'Цена пока не указана':money(state.paid)}</strong><small>уже оплачено / человек</small></div></div></article>`;
 if(state.route!=='D')$('#flights').innerHTML+=flightCard('02','НОВЫЕ ВНУТРЕННИЕ',state.route==='B'?(state.choice==='cheap'?'Sichuan · возврат TFU':'Sichuan 3U8580 / 3U8573'):'Air China CA4256 / Sichuan 3U6349','URC',state.route==='B'?'CTU':'CKG',state.route==='B'?[['23 ноября · CTU','08:25 → 12:00'],[state.choice==='cheap'?'30 ноября · TFU':'30 ноября · CTU',state.choice==='cheap'?'11:00 → 14:35':'13:10 → 16:55'],['Багаж основного CTU-тарифа','8 кг + 20 кг']]:[['23 ноября','13:05 → 16:55'],['30 ноября','12:15 → 16:30'],['Ручная / багаж','5 кг туда / 8 кг назад + 20 кг']],t.air,state.route==='B'?'chengdu':'domestic');
 $('#layover-note').innerHTML=`<span class="note-symbol">!</span><div><b>${state.route==='D'?'Без новых авиастыковок':'Самостоятельная стыковка в Урумчи'}</b><p>${t.detail}</p><p>${state.route==='D'?'Возвращение из Турфана 27-го; 30-го вечерний трансфер в аэропорт.':'При большой задержке следующий перевозчик не обязан бесплатно менять отдельный билет. Въезд, получение багажа и регистрация заново. Возвращение в Урумчи 29-го надёжнее, но его тариф отдельно не проверен.'}</p><p><b>Домой 1 декабря 02:00 — регистрация вечером 30 ноября.</b> Все часы местные. Карточки показывают найденные тарифы; ручная правка калькулятора их не меняет.</p></div>`;
 const railway=state.route==='B'?[['Чэнду ↔ Чунцин','成都东 ↔ 重庆北','~2 часа','примеры ~90–125 CNY в сторону','chengduTrain']]:state.route==='A'?[['Чунцин ↔ Чжанцзяцзе','重庆东 ↔ 张家界西','~2,5–3 часа','~181–225 CNY в сторону','chongTrain']]:[['Урумчи ↔ Турфан-Северный','乌鲁木齐 ↔ 吐鲁番北','~1 час','51,5 CNY скоростной / 24,5 CNY обычный','turpanTrain']];$('#train-table').innerHTML=table(['Пара городов','Китайские станции','В пути','Ориентир / чел.'],railway.map(([a,b,c,d,k])=>[a,b,c,d+'<br>'+link('Расписание',k)]));
 const hotels=[];for(const d of plan())if(!['В дороге','В самолёте','Дома'].includes(d.sleep)){const city=d.sleep;const last=hotels.at(-1);if(last&&last.city===city)last.dates.push(d.date);else hotels.push({city,dates:[d.date]});}
 const areas={'Урумчи':state.route==='D'?'Удобное метро; час ночного заезда и трансфер подтвердить':'У аэропорта; час ночного заезда и трансфер подтвердить','Чэнду':'Народный парк / Tianfu Square; метро','Чунцин':'Jiaochangkou / Jiefangbei; проверить вход и этаж','Улинъюань':'У восточного входа в лесной парк','Центр Чжанцзяцзе':'Ближе к отправлению на Тяньмэнь','Турфан':'Городской центр, не у далёкого северного вокзала'};
 $('#hotel-table').innerHTML=table(['Ночи с даты','Город','Где искать','Ночей'],hotels.map(h=>[h.dates.map(x=>date(x,{day:'2-digit',month:'2-digit'})).join(', '),h.city,areas[h.city],String(h.dates.length)]));}
function renderComparison(){const rows=[];for(const [r,list]of Object.entries(transport))for(const t of list){const c=calculate({...state,route:r,choice:t.id,air:null,paid:null,nights:null,extras:[],fx:70,room:160,food:80,reserve:30000});rows.push([routes[r].name+'<small>'+t.label+'</small>',money(t.air),'<b>'+money(c.additional)+'</b>',r==='A'?'Горы и больше подъёмников':r==='D'?'Минимум дороги, зима и история':'Городские вечера, панды и бани']);}$('#comparison').innerHTML='<p class="meta">Все суммы ниже — ещё потратить на человека, включая 30 000 ₸ резерва. Купленные Астана ↔ Урумчи добавить отдельно. Бани и другие дополнения не включены. Единые допущения: 9 ночей, номер 160 CNY / двое, еда 80 CNY / день, курс 70.</p>'+table(['Пара и авиация','Новые рейсы / чел.','Дополнительная смета / чел.','Для кого'],rows);}
function renderCalendar(){const trains=plan().filter(d=>d.mode==='train'||d.mode==='mixed');const list=[['Сейчас','Международные уже куплены. Сверить точный час прилёта 22-го, затем проверить оба внутренних участка на двух взрослых, багаж и итоговую цену.'],['После билетов',`Забронировать 8 основных ночей с двумя кроватями и при раннем прилёте короткую ночь 21→22. Банную ночёвку сначала подтвердить по паспорту, потом менять отель.`],...trains.map(d=>{const opens=new Date(d.date+'T12:00:00');opens.setDate(opens.getDate()-14);return[opens.toLocaleDateString('ru-RU',{day:'numeric',month:'long'}),`Открытие продажи на ${date(d.date)}: ${d.city}. Точный час зависит от станции.`];}),['За 5–7 дней','Погода, доступность парков и канаток, слоты панд / музеев, eSIM, страховка и адреса офлайн.'],['За 24–48 часов','Регистрация, изменения рейсов, терминалы, багаж и ночной трансфер.']];$('#calendar').innerHTML=list.map(([a,b])=>`<div><span>${a}</span><p>${b}</p></div>`).join('');}
function renderPacking(){const checklist=[...packing.filter(([id])=>!['bag','power','clothes'].includes(id)),['late-bag','Рюкзак по самому строгому участку','Купленный международный тариф ещё не известен. Найденные внутренние: 5 кг Air China / 8 кг Sichuan; проверить габариты и каждый участок.'],['late-power','Power bank с CCC/3C','Читаемая маркировка и отсутствие отзыва серии; только в ручную кладь.'],['layers','Тёплые слои и нескользящая обувь','Флис, дождевик, тёплый верх и запасные носки. Для гор — особенно.']];$('#packing').innerHTML=checklist.map(([id,t,d])=>`<label class="packing-item"><input type="checkbox" data-check="${id}" ${state.checks[id]===true?'checked':''}><span><b>${t}</b><small>${d}</small></span></label>`).join('');const progress=()=>$('#check-progress').textContent=checklist.filter(([id])=>state.checks[id]===true).length+' из '+checklist.length+' готово';$$('[data-check]').forEach(b=>b.onchange=()=>{state.checks[b.dataset.check]=b.checked;try{localStorage.setItem('china2026-late-checklist',JSON.stringify(state.checks));}catch{}progress();});progress();}
function renderRoute(){renderSpotlight();renderTransport();renderJourney();renderDay();renderControls();renderExtras();updateBudget();renderFlights();renderCalendar();}
for(const id of ['share-top','share-budget','share-final'])$('#'+id).onclick=share;
$$('[data-scope]').forEach(b=>b.onclick=()=>{state.scope=Number(b.dataset.scope);updateBudget();sync();});
$('#reset-budget').onclick=()=>{Object.assign(state,{fx:70,room:160,food:80,reserve:30000,air:null,nights:null,extras:[]});renderControls();renderExtras();updateBudget();sync();};
$('#share-dialog .dialog-close').onclick=()=>$('#share-dialog').close();
$('#print-plan').onclick=()=>{const d=$('#all-days').closest('details');d.open=true;window.print();};
let broIndex=0;const broAdvice=['Наш самый экстремальный аттракцион — уложиться в 7 кг.','В Чунцине первый этаж ещё надо найти.','Фото с пандой — после того, как выспимся.','Неоновый город, лапша, лучший бро. Всё, маршрут готов.'];$('#crew-advice').onclick=()=>$('#crew-quote').textContent=broAdvice[broIndex++%broAdvice.length];
renderRoute();renderComparison();renderPacking();
