import {routes,transport,getPlan,extras,sources,packing,credits,checkedAt} from './data.js';
import {mountJourneyAnimation} from './journey-animation.js';
const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)];
const money=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(Math.round(n))+' ₸';
const ext=(text,url)=>`<a class="text-link" href="${url}" target="_blank" rel="noopener noreferrer">${text}</a>`;
const link=(text,key)=>ext(text,sources[key]);
const date=(iso,format={day:'numeric',month:'long'})=>new Date(iso+'T12:00:00').toLocaleDateString('ru-RU',format);
const bound=(v,min,max,f)=>v!==null&&v!==''&&Number.isFinite(Number(v))?Math.max(min,Math.min(max,Number(v))):f;
const query=new URLSearchParams(location.search);
const state={route:routes[query.get('r')]?query.get('r'):'B',choice:query.get('t')||'split',day:0,scope:query.get('scope')==='2'?2:1,fx:bound(query.get('fx'),50,100,70),room:bound(query.get('room'),80,600,160),food:bound(query.get('food'),30,250,80),reserve:bound(query.get('reserve'),0,150000,30000),air:query.has('air')?bound(query.get('air'),0,1000000,null):null,extras:(query.get('extras')||'').split(',').filter(id=>extras.some(e=>e.id===id&&e.available.includes(query.get('r')||'B'))),checks:{}};
if(!transport[state.route].some(t=>t.id===state.choice))state.choice=transport[state.route][0].id;
if(state.extras.includes('bungee'))state.extras=state.extras.filter(id=>id!=='bridge');
try{const c=JSON.parse(localStorage.getItem('china2026-late-checklist')||'{}');if(c&&typeof c==='object'&&!Array.isArray(c))state.checks=c;}catch{}
const month=iso=>date(iso).replace(/^\d+\s+/, '');
const selected=()=>transport[state.route].find(t=>t.id===state.choice);
const plan=()=>getPlan(state.route,state.choice);
function calculate(s=state){const r=routes[s.route],t=transport[s.route].find(t=>t.id===s.choice),air=s.air??t.air;
 const rows=[['Все перелёты',air,'lime'],['Поезда',r.rail*s.fx,'purple'],[`Жильё · ${t.nights} ночей`,s.room*t.nights/2*s.fx,'blue'],[`Еда · ${t.foodDays} дней`,s.food*t.foodDays*s.fx,'orange'],['Входы и развлечения',r.entry*s.fx,'mint'],['Местный транспорт',r.local*s.fx,'gray'],['Связь и страховка',12000,'gray'],['Аэропорт Астаны',4000,'gray']];
 const active=extras.filter(e=>s.extras.includes(e.id)&&e.available.includes(s.route));if(active.length)rows.push(['Дополнительные впечатления',active.reduce((n,e)=>n+e.cny*s.fx,0),'orange']);
 const total=rows.reduce((n,r)=>n+r[1],0)+s.reserve;return{air,rows,total,left:500000-total,active};}
function sync(){const q=new URLSearchParams({r:state.route,t:state.choice});for(const [key,v]of Object.entries({scope:1,fx:70,room:160,food:80,reserve:30000}))if(state[key]!==v)q.set(key,state[key]);if(state.air!==null)q.set('air',state.air);if(state.extras.length)q.set('extras',state.extras.join(','));history.replaceState(null,'',location.pathname+'?'+q+location.hash);}
let toastTimer;function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
async function share(){sync();try{await navigator.clipboard.writeText(location.href);toast('Ссылка с вашим выбором скопирована');}catch{const dialog=$('#share-dialog');$('#share-url').value=location.href;dialog.showModal();$('#share-url').select();}}
const heading=(n,t,aside='')=>`<div class="section-heading"><div><p class="eyebrow">${n}</p><h2>${t}</h2></div>${aside?`<p>${aside}</p>`:''}</div>`;
const details=(title,body)=>`<details class="accordion"><summary>${title}<span class="plus">+</span></summary><div class="details-body">${body}</div></details>`;
const table=(heads,rows)=>`<table class="data-table"><thead><tr>${heads.map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
$('#planner-content').innerHTML=`
<section class="departure-deal"><div><p class="eyebrow">ОДИН ДЕНЬ МЕНЯЕТ СМЕТУ</p><h3>26 ноября — заметно дешевле.</h3><p>Астана ↔ Урумчи прямыми FlyArystan: <b>66 445 ₸ / человек</b>, 26 ноября — 4 декабря. Это 9 календарных дней. Для Чэнду и Чунцина <b>все четыре рейса — 200 115 ₸</b>.</p></div><div>${link('Открыть найденные даты','urc')}<small>Снимок выдачи ${checkedAt}; цена может измениться.</small></div></section>
<section class="block compact-block" id="transport">${heading('02 / ВЫБИРАЕМ ДОРОГУ','Удобство тоже можно сравнить.')}<div id="transport-options" class="transport-options" role="group" aria-label="Вариант перелётов"></div><div id="transport-note" class="travel-note"></div></section>
<section id="journey-section" class="journey-section"><div class="minor-heading"><h3>Как движемся</h3><span class="meta">Самолёты, поезда и прогулки · нажмите ▶</span></div><div id="trip-animation" class="trip-animation"></div><div id="inclusions" class="inclusions"></div></section>
<section id="days" class="block">${heading('03 / НЕ ГАЛОЧКИ, А ПРОГУЛКИ','Теперь у каждого города есть время.','Даты учитывают декабрь.<br>Все часы местные.')}<div id="day-tabs" class="day-tabs" role="tablist" aria-label="Дни поездки"></div><article id="day-panel" class="day-panel" role="tabpanel" tabindex="0"></article>${details('Весь маршрут на одной странице','<div id="all-days"></div>')}</section>
<section id="budget" class="block">${heading('04 / ВАШИ 500 ТЫСЯЧ','Считаем всю поездку.')}<div class="segmented" role="group" aria-label="Показывать бюджет"><button data-scope="1">На одного</button><button data-scope="2">На двоих</button></div><div class="budget-layout"><div class="budget-editor"><div id="budget-controls"></div><div class="extras-heading"><h3>Добавим впечатлений?</h3><p>Дополнения требуют свободного времени в программе. Суммы — на человека.</p></div><div id="extras" class="extras"></div></div><aside class="budget-result"><div class="budget-result-top"><span id="budget-scope"></span><span id="budget-status" class="budget-badge"></span></div><div id="budget-total" class="budget-total"></div><p id="reserve-note"></p><div class="budget-meter"><span id="meter-fill"></span></div><div id="budget-left" class="budget-left"></div><div id="breakdown" class="budget-breakdown"></div><div class="budget-bro"><img src="assets/friend-sticker.png" alt="" width="72" height="80" loading="lazy"><p id="budget-bro-quote"></p></div><p class="budget-disclaimer">Смета на человека, не пакетный тур. Ночёвка в Урумчи включена для отдельных билетов. Доплата за багаж FlyArystan не включена. Входы, транспорт, связь и страховка — плановые лимиты.</p><button class="button wide" id="share-budget">Отправить этот вариант другу</button><button class="reset-button" id="reset-budget">Вернуть исходную смету</button></aside></div></section>
<section id="tickets" class="block">${heading('05 / ПОЛНАЯ ЦЕПОЧКА','Билеты и время — рядом.','Найденные тарифы на человека.<br>Не оплаченные бронирования.')}<div id="flights" class="flight-grid"></div><div id="layover-note" class="travel-note"></div>${details('Поезда: сколько ехать и какие вокзалы','<p>Это ориентиры по доступным расписаниям, не подтверждённые ноябрьские билеты. На поезда действует окно продажи 15 дней с учётом дня отправления. Предзаказ посредника ещё не билет.</p><div id="train-table" class="table-scroll"></div>'+link('Официальное правило 12306','railWindow'))}${details('Жильё: районы, ночи и две кровати','<p>В расчёте 160 CNY за номер на двоих / ночь, около 5 600 ₸ с человека. Это целевая цена, наличие не проверено. Нужны две кровати, отопление, оформление иностранных гостей и подходящий заезд.</p><div id="hotel-table" class="table-scroll"></div><p class="meta">В Урумчи подтвердить заезд после 01:00 и трансфер. Не бронировать ночь 27→28 вместо 26→27.</p>')}</section>
<section id="compare" class="block">${heading('06 / ДАТЫ И АЛЬТЕРНАТИВЫ','Что мы действительно нашли.','Сравниваем сроки, время<br>и полную сумму.')}<div id="comparison" class="comparison-scroll"></div>${details('Почему вылет 26-го выгоднее: сравнение соседних дат',`<p>Цены ниже — только Астана ↔ Урумчи. Внутренние перелёты и поезда оплачиваются дополнительно. Длительность различается: 9 дней против 10.</p><div class="table-scroll">${table(['Даты','Туда-обратно / чел.','Что с дорогой'],[
 ['24 ноября — 3 декабря','132 167 ₸',`Туда через Актау, около 12 ч 20 мин. Обратный участок отдельно не проверен. ${link('Выдача','urc24')}`],
 ['25 ноября — 4 декабря','102 980 ₸',`Туда SCAT через Шымкент, 9 ч 40 мин. Возврат и итоговый тариф не подтверждены. ${link('Выдача','urc25')}`],
 ['25 ноября — 4 декабря','122 620 ₸',`Прямые: China Southern туда + FlyArystan обратно. Оба участка проверены. ${link('Проверить','urc25')}`],
 ['26 ноября — 4 декабря','66 445 ₸',`Оба прямые FlyArystan. Проверен итог на двоих 132 890 ₸. ${link('Проверить','urc')}`],
 ['26 ноября — 5 декабря','105 734 ₸',`Туда прямо, обратно через Инин 9 ч 05 мин. Составной тариф, условия пересадки требуют проверки. ${link('Выдача','urc26long')}`]
 ])}</div><p>Самая низкая проверенная цена из этих дат — 26→4. Это не утверждение о самом дешёвом билете во всём Китае.</p>`)}
<div class="insight-grid"><article class="insight"><span class="insight-number">56<span>тыс. ₸</span></span><h3>Сдвиг на один день</h3><p>На международных прямых рейсах 26→4 дешевле 25→4 на 56 175 ₸. Но поездка становится короче на день.</p></article><article class="insight"><span class="insight-number">~2<span>часа</span></span><h3>Между Чэнду и Чунцином</h3><p>Вместо цепочки ночных переездов — короткий поезд. Сравнивайте вокзалы: дальний вокзал может съесть выигрыш.</p></article><article class="insight"><span class="insight-number">+2<span>дня</span></span><h3>Ловушка дешёвого тарифа</h3><p>У Астана ↔ Чунцин цена около 291 тысячи выглядела хорошо, но выбранный возврат из-за длинной пересадки прилетал 6 декабря. Под ваши 10 дней не подходит.</p></article></div>
${details('Ещё дешевле, Стена и длинные поезда',`<p><b>Урумчи + Турфан:</b> минимальная дальность после въезда. Только международная авиация 66 445 ₸, вся поездка предварительно около 220–290 тысяч с резервом. Это черновой диапазон без поиска конкретного жилья; поздний ноябрь холодный, впечатления совсем другие. Нет «Аватара», Стены и Шаолиня.</p><p><b>Пекин + Тяньцзинь:</b> логичная пара для Великой стены. Свежая полная авиасвязка на новые даты в этом сравнении не подтверждена, поэтому цена не выдумана. У Мутяньюя зимой более короткий день. ${link('Часы работы','wall')}</p><p><b>Из Урумчи далеко поездом:</b> текущий ориентир до Сианя — около 14 часов и 735,5 CNY на скоростном либо около 25 часов и 446,5 CNY на жёсткой спальной полке, в одну сторону. Два таких переезда забирают 2–3 дня и не гарантируют экономии против дешёвой авиации. ${link('Сравнить поезда','urcTrain')}</p><p>Алматы, наземный въезд и долгие пересадки можно рассматривать отдельно, но их выгода в полной поездке на 10 дней здесь не доказана.</p>`)}
</section>
<section id="prepare" class="block">${heading('07 / ПЕРЕД ВЫЛЕТОМ','Собрать рюкзак. И не забыть Китай.')}<div class="prepare-grid"><div><div class="minor-heading"><h3>Личный чек-лист</h3><span class="meta" id="check-progress"></span></div><p class="meta">Сохраняется в этом браузере. У друга свой список.</p><div id="packing"></div></div><div><h3>Когда покупать</h3><div id="calendar" class="calendar"></div></div></div><div class="practical-grid">
${details('Паспорт, въезд и отели',`<p>Для граждан Казахстана с обычными паспортами туристический въезд по соглашению без визы: до 30 дней за один въезд и до 90 за 180 дней. ${link('МИД Казахстана','visa')}</p><p>Сохранить обратный билет, адрес первого отеля по-китайски, страховку и копию паспорта офлайн. Отель оформляет регистрацию проживания. Проверить срок действия паспорта и действующие правила до оплаты билетов. ${link('Форма въездной карты NIA','arrival')}</p>`)}
${details('Багаж, связь и деньги',`<p>Самая дешёвая международная связка FlyArystan: ручная кладь 7 кг, сдаваемый багаж не включён; тариф без возврата и изменения. У внутреннего Air China в маршруте с «Аватаром» норма ручной клади 5 кг, у Sichuan — 8 кг, багаж 20 кг. Сквозная Air China / прямой Сиань в выдаче: 5 кг + 23 кг. Перед оплатой сверить каждый участок. ${link('Ручная кладь FlyArystan','baggage')}</p><p>Для внутренних рейсов Китая выбирать power bank с чёткой маркировкой CCC/3C, не из отозванной серии. Не сдавать его в багаж. ${link('Правило CAAC','power')}</p><p>Заранее настроить Alipay, проверить доступную оплату вашей картой / Kaspi, оставить резервную карту и немного наличных CNY. ${link('Kaspi: оплата Alipay+','kaspi')}</p><p>Выбрать туристическую eSIM с покрытием в Китае и условиями доступа к нужным приложениям, проверить поддержку телефона. Установить переводчик с китайским офлайн, сохранить билеты, станции и адреса. Интернет и страховка в смете — лимит 12 000 ₸, не конкретный найденный продукт.</p>`)}
${details('Поздний ноябрь и экстремальные развлечения',`<p>Одевайтесь слоями: тёплый верх, флис, дождевик, нескользящая обувь и запасные носки. Горные тропы холоднее города, туман может закрыть панорамы. Сейчас точного прогноза на поездку нет: проверить его за 5–7 дней.</p><p>«Два города» означает две базы для прогулок. Урумчи — транзит; Шаолинь, Хуашань или Улон — только дневные выезды по желанию. Великая стена не входит ни в одну из трёх базовых пар.</p><p>Тяньмэнь: реконструкция верхнего участка длинной канатки объявлена с ноября 2025. Схему доступа к вашей дате проверить до покупки. ${link('Объявление','tianmen')}</p><p>Банджи: оператор публикует 1 998 CNY + 178 CNY вход на мост, ограничения 16–65 лет и 40–90 кг. Подтвердить доступность и покрытие страховки. При базовой смете «Аватара» прыжок выводит поездку за 500 тысяч. ${link('Оператор','bungee')}</p>`)}
</div></section>
<section class="final-card"><div><p class="eyebrow">ГОТОВЫ ОБСУДИТЬ ВДВОЁМ</p><h2>Выберите характер поездки.</h2><p>Мой выбор — Чэнду + Чунцин через Урумчи 26 ноября. Если главное горы — вариант с «Аватаром». Если Шаолинь и простая авиация — прямой Сиань.</p></div><div><button class="button" id="share-final">Скопировать наш выбор ↗</button><a class="pdf-link" href="guide-25-november.md" download>Скачать руководство для обсуждения</a><button class="reset-button" id="print-plan">Распечатать этот маршрут</button></div></section>
${details('Источники, цены и фотографии',`<p>Проверено ${checkedAt}. Авиавыдача на 2 взрослых, суммы на человека, без финальной оплаты. Курс НБК на 7 октября: 67,66 ₸ за CNY; расчётный курс 70 ₸ оставляет небольшой запас. Это не прогноз. ${link('Курс НБК','fx')}</p><div class="source-links">${[['Астана ↔ Урумчи','urc'],['Урумчи ↔ Чэнду','chengdu'],['Урумчи ↔ Чунцин','domestic'],['Астана ↔ Сиань','xian'],['Air China до Чунцина','through'],['Панды: 55 CNY','panda'],['Парк Чжанцзяцзе: тариф 2026','park'],['12306','rail'],['Пешеходные маршруты Чунцина','chongqingWalk']].map(([t,k])=>link(t,k)).join('')}</div><p>Дневные часы прогулок и расходы — наш план. Поезда приведены по доступной осенней выдаче; ноябрьские отправления подтвердить при открытии продаж. Точный курс списания, комиссия, багаж и цена отеля могут изменить итог.</p>${credits.map(c=>`<p class="credit">${c.name} · ${c.author} · ${ext(c.license,c.licenseUrl)} · ${ext('Фото',c.url)}</p>`).join('')}<p class="meta">Фотография Мутяньюя относится к архиву первой версии. Старый PDF на 11–20 ноября не является текущим руководством. Фото друга добавлено по вашей просьбе; реплики шуточные.</p>`)}
<dialog id="share-dialog" class="share-dialog"><button class="dialog-close" aria-label="Закрыть">×</button><h2>Наш выбор</h2><p>Скопируйте ссылку. Она сохраняет маршрут и расчёт, но не синхронизирует изменения между вами.</p><input id="share-url" readonly aria-label="Ссылка на выбранный маршрут"></dialog>`;
function renderSpotlight(){const r=routes[state.route],t=selected(),c=calculate();$('#route-choices').innerHTML=Object.entries(routes).map(([key,r])=>{const total=calculate({...state,route:key,choice:transport[key][0].id,air:null,extras:[],fx:70,room:160,food:80,reserve:30000}).total;return`<button type="button" class="route-choice ${key===state.route?'selected':''}" data-route="${key}" aria-pressed="${key===state.route}"><span class="route-letter">${key}</span><span class="route-label"><b>${r.name}</b><small>${r.tag}</small></span><span class="route-price">~${money(total)}<small>вся поездка / чел.</small></span></button>`;}).join('');
 $('#route-spotlight').innerHTML=`<div class="spotlight-copy"><p class="eyebrow">МАРШРУТ ${state.route} / ${r.tag}</p><h3>${r.title}</h3><p>${state.route==='B'&&state.choice==='through'?r.description.replace('шесть ночей в них','восемь ночей в них'):r.description}</p><div class="quick-stats"><span><b id="spot-air">${money(c.air)}</b>все рейсы / чел.</span><span><b>${t.days} дней</b>${t.span}</span><span><b id="spot-left">${money(Math.abs(c.left))}</b><span id="spot-left-label">${c.left>=0?'свободно до лимита':'сверх лимита'}</span></span></div></div><div class="spotlight-visual">${state.route==='C'?'<div class="city-poster"><span>西安</span><span>洛阳</span><small>СИАНЬ × ЛОЯН</small><div class="poster-wall" aria-hidden="true">▥ ▥ ▥ ▥ ▥</div></div>':`<img src="assets/${r.image}" alt="${r.place}" width="1280" height="853">`}<div class="photo-caption"><span>${state.route==='C'?'少林':r.han}</span><strong>${state.route==='C'?'Шаолинь — из Лояна':r.place}</strong><small>${state.route==='C'?'Иллюстрация. Великая стена сюда не входит.':r.caption}</small></div></div>`;
 $$('[data-route]').forEach(b=>b.onclick=()=>{state.route=b.dataset.route;state.choice=transport[state.route][0].id;state.air=null;state.day=0;state.extras=state.extras.filter(id=>extras.some(e=>e.id===id&&e.available.includes(state.route)));renderRoute();sync();});$('#crew-quote').textContent=r.quote;}
function renderTransport(){$('#transport-options').innerHTML=transport[state.route].map(t=>`<button class="transport-choice ${t.id===state.choice?'selected':''}" data-transport="${t.id}" aria-pressed="${t.id===state.choice}"><span>${t.label}</span><b>${money(t.air)}</b><small>все рейсы / чел. · ${t.days} дней</small></button>`).join('');$('#transport-note').innerHTML=`<span class="note-symbol">i</span><div><b>${selected().span} · ${selected().days} календарных дней</b><p>${selected().detail}</p></div>`;$$('[data-transport]').forEach(b=>b.onclick=()=>{state.choice=b.dataset.transport;state.air=null;state.day=0;renderRoute();sync();});}
function renderJourney(){const days=plan();$('#inclusions').innerHTML=`<div>${routes[state.route].included.map(t=>`<span class="included">✓ ${t}</span>`).join('')}</div><p>${routes[state.route].missed}</p>`;mountJourneyAnimation({route:state.route,span:selected().span,scenes:days.map(d=>({...d,detail:d.steps.map(([t,p])=>p).join(' ')})),onDay:iso=>{const i=days.findIndex(d=>d.date===iso);if(i>=0){state.day=i;renderDay();}}});}
function renderDay(){const days=plan();state.day=Math.min(state.day,days.length-1);const d=days[state.day];$('#day-tabs').style.setProperty('--day-count',days.length);$('#day-tabs').innerHTML=days.map((d,i)=>`<button class="day-tab ${i===state.day?'active':''}" role="tab" id="day-${i}" data-day="${i}" aria-controls="day-panel" aria-selected="${i===state.day}" tabindex="${i===state.day?0:-1}"><span>День ${i+1}</span><b>${Number(d.date.slice(8))}</b><small>${month(d.date)}</small></button>`).join('');$('#day-panel').setAttribute('aria-labelledby','day-'+state.day);$('#day-panel').innerHTML=`<div class="day-heading"><span class="day-big">${Number(d.date.slice(8))}<small>${month(d.date).toUpperCase()}</small></span><span class="day-city">${d.city}</span><div class="night-label"><span>ГДЕ СПИМ</span><b>${d.sleep}</b></div></div><div class="day-story"><h3>${d.title}</h3><div class="day-steps">${d.steps.map(([time,text])=>`<div><span>${time}</span><p>${text}</p></div>`).join('')}</div><div class="day-tip"><b>На заметку</b><p>${d.tip}</p></div></div>`;
 $('#all-days').innerHTML=days.map((d,i)=>`<article class="full-day"><button class="compact-day" data-jump="${i}"><span>${date(d.date,{day:'2-digit',month:'2-digit'})}</span><b>${d.title}</b><small>${d.sleep}</small></button><div class="full-day-detail">${d.steps.map(([t,p])=>`<p><b>${t}</b> — ${p}</p>`).join('')}<p class="meta">${d.tip}</p></div></article>`).join('');
 $$('[data-day]').forEach(b=>{b.onclick=()=>{state.day=Number(b.dataset.day);renderDay();$('#day-'+state.day).focus({preventScroll:true});};b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();state.day=e.key==='Home'?0:e.key==='End'?days.length-1:Math.max(0,Math.min(days.length-1,state.day+(e.key==='ArrowRight'?1:-1)));renderDay();$('#day-'+state.day).focus();};});$$('[data-jump]').forEach(b=>b.onclick=()=>{state.day=Number(b.dataset.jump);renderDay();$('#days').scrollIntoView();});}
function renderControls(){const t=selected();$('#budget-controls').innerHTML=`<h3>Настройте под себя</h3><p class="muted">Цены жилья — за номер на двоих. Остальное на человека.</p><div class="control-group"><label for="fx">Расчётный курс юаня <output id="fx-output">${state.fx} ₸</output></label><input id="fx" type="range" min="50" max="100" value="${state.fx}"><p class="input-help">НБК: 67,66 ₸ на 7 октября. В смете 70 ₸ с запасом.</p></div><div class="control-pair"><div><label for="room">Номер на двоих / ночь, CNY</label><input id="room" type="number" min="80" max="600" value="${state.room}"><p class="input-help">${t.nights} ночей; половина стоимости каждому.</p></div><div><label for="food">Еда / день / человек, CNY</label><input id="food" type="number" min="30" max="250" value="${state.food}"><p class="input-help">${t.foodDays} дней расходов. Неполные дни перелётов покрывает резерв.</p></div></div><div class="control-pair"><div><label for="reserve">Резерв / человек, ₸</label><input id="reserve" type="number" min="0" max="150000" step="5000" value="${state.reserve}"></div><div><label for="air">Все рейсы / человек, ₸</label><input id="air" type="number" min="0" max="1000000" value="${calculate().air}"><p class="input-help">Подставьте цену после багажа и комиссии.</p></div></div><p class="quiet-note">Входы и развлечения: ${routes[state.route].entry} CNY. Местные дороги: ${routes[state.route].local} CNY. Это лимиты, точные брони ещё не сделаны.</p>`;
 for(const [key,rules]of Object.entries({fx:[50,100,70],room:[80,600,160],food:[30,250,80],reserve:[0,150000,30000],air:[0,1000000,t.air]})){$('#'+key).oninput=e=>{if(!e.target.value)return;state[key]=bound(e.target.value,...rules);$('#fx-output').textContent=state.fx+' ₸';renderExtras();updateBudget();sync();};$('#'+key).onchange=e=>e.target.value=state[key];}}
function renderExtras(){$('#extras').innerHTML=extras.filter(e=>e.available.includes(state.route)).map(e=>`<label class="extra-option ${state.extras.includes(e.id)?'checked':''}"><input type="checkbox" value="${e.id}" ${state.extras.includes(e.id)?'checked':''}><span class="extra-check"></span><span><b>${e.title}</b><small>${e.detail}</small></span><strong>+${money(e.cny*state.fx)}</strong></label>`).join('');$$('.extra-option input').forEach(b=>b.onchange=()=>{state.extras=state.extras.filter(id=>id!==b.value);if(b.checked){if(b.value==='bridge')state.extras=state.extras.filter(id=>id!=='bungee');if(b.value==='bungee')state.extras=state.extras.filter(id=>id!=='bridge');state.extras.push(b.value);}renderExtras();updateBudget();sync();});}
function updateBudget(){const c=calculate(),m=state.scope;$$('[data-scope]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.scope)===m);b.setAttribute('aria-pressed',String(Number(b.dataset.scope)===m));});$('#budget-scope').textContent=m===1?'НА ЧЕЛОВЕКА':'НА ДВОИХ';$('#budget-total').textContent=money(c.total*m);$('#reserve-note').textContent='Включая '+money(state.reserve*m)+' резерва';$('#budget-status').textContent=c.left>=0?'В бюджете':'Выше лимита';$('#budget-status').classList.toggle('over',c.left<0);$('#meter-fill').style.width=Math.min(100,c.total/5000)+'%';$('#meter-fill').classList.toggle('over',c.left<0);$('#budget-left').innerHTML=`<span>${c.left>=0?'Ещё свободно':'Превышение'}</span><b class="${c.left<0?'negative':''}">${money(Math.abs(c.left)*m)}</b><small>Лимит ${money(500000*m)}</small>`;$('#breakdown').innerHTML=c.rows.map(([label,n,color])=>`<div><span><i class="dot ${color}"></i>${label}</span><b>${money(n*m)}</b></div>`).join('')+`<div class="reserve-line"><span>Резерв</span><b>${money(state.reserve*m)}</b></div>`;$('#spot-air').textContent=money(c.air);$('#spot-left').textContent=money(Math.abs(c.left));$('#spot-left').classList.toggle('negative',c.left<0);$('#spot-left-label').textContent=c.left>=0?'свободно до лимита':'сверх лимита';$('#budget-bro-quote').textContent=c.left<0?'Бро, прыжок крутой, но калькулятор тоже умеет падать.':'На лапшу и внезапные приключения остаётся. Одобряю.';}
function flightCard(no,label,company,from,to,lines,price,key){return`<article class="flight-card"><div class="ticket-top"><span>${no} / ${label}</span><b>${company}</b></div><div class="airport-pair"><strong>${from}</strong><span class="flight-line">✈</span><strong>${to}</strong></div><div class="flight-times">${lines.map(([a,b])=>`<p><b>${a}</b><span>${b}</span></p>`).join('')}</div><div class="ticket-bottom"><div><strong>${money(price)}</strong><small>туда-обратно / человек</small></div>${link('Проверить тариф',key)}</div></article>`;}
function renderFlights(){const t=selected();if(state.route==='C'){$('#flights').innerHTML=flightCard('01','ПРЯМЫЕ РЕЙСЫ','Air China CA792 / CA791','NQZ','XIY',[['25 → 26 ноября','21:45 → 06:10'],['4 декабря','17:15 → 20:20'],['Время полёта','5 ч 25 / 6 ч 05']],254547,'xian');}
 else if(state.choice==='through'){$('#flights').innerHTML=flightCard('01','ОДНА АВИАСВЯЗКА','Air China · Сиань + Пекин','NQZ','CKG',[['25 ноября, старт','21:45'],['26 ноября, Чунцин','15:40'],['4 декабря, старт / дома','07:15 / 20:20'],['Весь путь туда / обратно','14 ч 55 / 16 ч 05']],254467,'through');}
 else{$('#flights').innerHTML=flightCard('01','МЕЖДУНАРОДНЫЕ','FlyArystan FS7961 / FS7962','NQZ','URC',[['26 → 27 ноября','19:30 → 01:00'],['4 декабря','02:00 → 01:50'],['Ручная кладь','7 кг, без багажа']],66445,'urc')+flightCard('02','ВНУТРИ КИТАЯ',state.route==='B'?'Sichuan Airlines':'Air China + Sichuan','URC',state.route==='B'?'CTU':'CKG',state.route==='B'?[['27 ноября · CTU','08:25 → 12:00'],[state.choice==='cheap'?'3 декабря · TFU':'3 декабря · CTU',state.choice==='cheap'?'11:00 → 14:35':'13:10 → 16:55'],['Найденный багаж','8 кг + 20 кг']]:[['27 ноября · CA4256','13:05 → 16:55'],['3 декабря · 3U6349','12:15 → 16:30'],['Ручная туда / обратно','5 кг / 8 кг']],t.air-66445,state.route==='B'?'chengdu':'domestic');}
 $('#flights').style.gridTemplateColumns='';$('#layover-note').innerHTML=`<span class="note-symbol">!</span><div><b>${state.choice==='through'||state.route==='C'?'Проще с международной авиацией':'Самостоятельные пересадки: отдельные билеты'}</b><p>${t.detail}</p><p>${state.choice==='split'||state.choice==='cheap'?'При задержке первого рейса следующий перевозчик не обязан бесплатно менять билет. В Урумчи въезд, получение багажа и регистрация заново. Рейс домой 4 декабря в 02:00: быть в аэропорту вечером 3-го.':'Проверить терминалы, багаж и все условия в окончательном тарифе. В сквозной связке Сиань и Пекин — транзит, а не дополнительные города отдыха.'}</p><p>Все часы местные. Китай на 3 часа впереди Астаны. Сумма в карточках — найденная цена; ручная правка калькулятора её не меняет.</p></div>`;
 const railway=state.route==='B'?[['Чэнду ↔ Чунцин','成都东 ↔ 重庆北','~2 часа','~96–125 CNY в сторону','chengduTrain']]:state.route==='A'?[['Чунцин ↔ Чжанцзяцзе','重庆东 ↔ 张家界西','~2,5–3 часа','~181–225 CNY в сторону','chongTrain']]:[['Сиань ↔ Лоян','西安北 ↔ 洛阳龙门','~1 ч 15–40 мин','~175 CNY в сторону','xianTrain']];$('#train-table').innerHTML=table(['Пара городов','Китайские станции','В пути','Ориентир / чел.'],railway.map(([a,b,c,d,k])=>[a,b,c,d+'<br>'+link('Расписание',k)]));
 const hotels=[];for(const d of plan())if(!['В дороге','В самолёте','Дома'].includes(d.sleep)){const city=d.sleep.includes('Урумчи')?'Урумчи':d.sleep;const last=hotels.at(-1);if(last&&last.city===city)last.dates.push(d.date);else hotels.push({city,dates:[d.date]});}
 const areas={'Урумчи':'У аэропорта; подтвердить поздний заезд и ночной трансфер','Чэнду':'Народный парк / Tianfu Square; удобное метро','Чунцин':'Jiaochangkou / Jiefangbei; проверить настоящий вход и лестницы','Улинъюань':'У восточного входа в лесной парк','Центр Чжанцзяцзе':'У отправления на Тяньмэнь','Сиань':'У метро Zhonglou или Yongningmen','Лоян':'У метро с доступом к старому городу и вокзалу'};
 $('#hotel-table').innerHTML=table(['Ночи с даты','Город','Где искать','Ночей'],hotels.map(h=>[h.dates.map(x=>date(x,{day:'2-digit',month:'2-digit'})).join(', '),h.city,areas[h.city],String(h.dates.length)]));}
function renderComparison(){const rows=[];for(const [r,list]of Object.entries(transport))for(const t of list){const c=calculate({...state,route:r,choice:t.id,air:null,extras:[],fx:70,room:160,food:80,reserve:30000});rows.push([routes[r].name+'<small>'+t.label+'</small>',money(t.air),'<b>'+money(c.total)+'</b>',t.days+' дней',r==='A'?'Горы; больше платных входов':r==='C'?'Шаолинь; прямой рейс':'Больше свободного бюджета']);}$('#comparison').innerHTML=table(['Пара и авиация','Все рейсы / чел.','Вся смета / чел.','Срок','Для кого'],rows);}
function renderCalendar(){const trains=plan().filter(d=>d.mode==='train'||d.mode==='mixed');const list=[['Сейчас','Сначала проверить сразу всю цепочку рейсов на двух взрослых, багаж, даты прилёта и финальную сумму. Потом покупать, не наоборот.'],['После билетов',`Забронировать ${selected().nights} ночей с двумя кроватями; включить бесплатную отмену, если цена разумна.`],...trains.map(d=>{const opens=new Date(d.date+'T12:00:00');opens.setDate(opens.getDate()-14);return[opens.toLocaleDateString('ru-RU',{day:'numeric',month:'long'}),`Открытие продажи на ${date(d.date)}: ${d.city}. Точный час зависит от станции.`];}),['За 5–7 дней','Погода, доступность парков и канаток, слоты панд / музеев, eSIM, страховка и адреса офлайн.'],['За 24–48 часов','Регистрация, изменения рейсов, терминалы, багаж и ночной трансфер.']];$('#calendar').innerHTML=list.map(([a,b])=>`<div><span>${a}</span><p>${b}</p></div>`).join('');}
function renderPacking(){const checklist=[...packing.filter(([id])=>!['bag','power','clothes'].includes(id)),['late-bag','Рюкзак по самому строгому участку','7 кг FlyArystan; для Air China внутри Китая 5 кг. Сверить габариты своего тарифа.'],['late-power','Power bank с CCC/3C','Читаемая маркировка и отсутствие отзыва серии; только в ручную кладь.'],['layers','Тёплые слои и нескользящая обувь','Флис, дождевик, тёплый верх и запасные носки. Для гор — особенно.']];$('#packing').innerHTML=checklist.map(([id,t,d])=>`<label class="packing-item"><input type="checkbox" data-check="${id}" ${state.checks[id]===true?'checked':''}><span><b>${t}</b><small>${d}</small></span></label>`).join('');const progress=()=>$('#check-progress').textContent=checklist.filter(([id])=>state.checks[id]===true).length+' из '+checklist.length+' готово';$$('[data-check]').forEach(b=>b.onchange=()=>{state.checks[b.dataset.check]=b.checked;try{localStorage.setItem('china2026-late-checklist',JSON.stringify(state.checks));}catch{}progress();});progress();}
function renderRoute(){renderSpotlight();renderTransport();renderJourney();renderDay();renderControls();renderExtras();updateBudget();renderFlights();renderCalendar();}
for(const id of ['share-top','share-budget','share-final'])$('#'+id).onclick=share;
$$('[data-scope]').forEach(b=>b.onclick=()=>{state.scope=Number(b.dataset.scope);updateBudget();sync();});
$('#reset-budget').onclick=()=>{Object.assign(state,{fx:70,room:160,food:80,reserve:30000,air:null,extras:[]});renderControls();renderExtras();updateBudget();sync();};
$('#share-dialog .dialog-close').onclick=()=>$('#share-dialog').close();
$('#print-plan').onclick=()=>{const d=$('#all-days').closest('details');d.open=true;window.print();};
let broIndex=0;const broAdvice=['Наш самый экстремальный аттракцион — уложиться в 7 кг.','В Чунцине первый этаж ещё надо найти.','Фото с пандой — после того, как выспимся.','Неоновый город, лапша, лучший бро. Всё, маршрут готов.'];$('#crew-advice').onclick=()=>$('#crew-quote').textContent=broAdvice[broIndex++%broAdvice.length];
renderRoute();renderComparison();renderPacking();
